#library(shiny)
library(bslib)
library(tidyverse)
library(readxl)
library(data.table)
library(thematic)
library(shinyBS)   # tooltips, maybe - shinyBS uses bootstrap 3 and bslib uses 5
library(DT)
library(shinydashboard)
library(shinyWidgets)
library(htmltools)
library(plotly)



# load source files -------------------------------------------------------
all_files <- c(
  list.files("functions", full.names = TRUE)
#               ,list.files("processing_scripts", full.names = TRUE) # this breaks it at the moment
               )

data_list <- list()


# reading in xlsx and R files only - note
for (file in all_files) {
  if (grepl("\\.R$", file)) {
    source(file)
  }
}


source("globals.R")
source("read_from_user_inputs.R")


# create a graph ----------------------------------------------------------


create_graph <- function(data, indicator){
}



# ui ----------------------------------------------------------------------


ui <- function(request) {
  tagList(
    # Leave this function for adding external resources
    # Application UI logic
    title = "",
    page_navbar(
      theme = bs_theme(
        version = 5,
        fg = "#0d204d", # this has the same CMYK values as #173A89 but 70% saturation on black as opposed to 46%
        primary = "#173A89", #2A8627
        base_font = font_google("Inter"),
        font_scale = NULL,
        preset = "pulse",
        bg = "#fff"
      ),
      tags$style(HTML(
        '
      .nav.navbar-nav .form-group.shiny-input-container {margin-bottom: 0; height: 50px;}
      .nav.navbar-nav .form-group.shiny-input-container > label {display: inline;}
        '
      )),
      title = "TEA-CART",
      sidebar = sidebar(fileInput("user_inputs_upload",
                                  "Upload User Inputs",
                                  accept = c(".xlsx")),
                        bsTooltip(id = "user_inputs_upload",
                                  "Upload the file generated by the TEA-CART tool with user inputs.",
                                  options = list(container = "body"),
                                  placement = "right"),
                        downloadButton("user_inputs_download", "Download User Inputs"),
                        p("Remember to save and download data regularly while
                          entering or updating values. "),
                        nav_spacer(),
                        nav_spacer(),
                        nav_spacer(),
                        downloadButton("pdf_report","Download Summary Report")),
      nav_panel(title = "Welcome",
                p(),
                #    h2("Transportation Evaluation and Carbon Reduction Tool (TEA-CART)"),
                h3("About"),
                p(),
                p("The Transportation Evaluation and Carbon Reduction Tool (TEA-CART) is a
      comprehensive and dynamic tool aimed at assisting states with selecting
      and prioritizing transportation capital program investments to effectively
      support greenhouse gas (GHG) reduction. The tool is designed to accept
      inputs typically available during the programming process. It provides
      key outputs including:"),
      tags$ul(tags$li(p("A baseline inventory and forecast of GHG emissions.")),
              tags$li(p("GHG impacts of a capital program or a hypothetical set
                      of capital projects.")),
              tags$li(p("Information on cost-effectiveness of various project
                      types."))),
      h3("Version"),
      p("Based on TEA-CART Excel Model Version 1.8"),
      p("Shiny App last updated December 13, 2023"),
      p("draft User Interface (UI) under development by Cambridge Systematics, Inc."),
      p("under contract to Georgetown Climate Center"),
      p("© Georgetown Climate Center"),
      ),
      nav_panel(title = "Inputs",
                navset_card_pill(
                  nav_panel(title = "Baseline",
                            fluidRow(
                              DT::dataTableOutput("test_data")
                            ),
                            fluidRow(
                              column(6,
                                     
                                     tabPanel(title = "Key Inputs"),
                                     p("Select the state, years, and scope of baseline GHG forecast."),
                                     
                                     selectInput("state_input",
                                                 "State:",
                                                 selected = NULL,
                                                 state.name),
                                     numericInput("base_year",
                                                  "Base Year:",
                                                  value = 2021,
                                                  min = 2021,
                                                  max = 2050,
                                                  step = 1),
                                     p(" "),
                                     numericInput("horizon_year_1",
                                                  "Horizon Year 1:",
                                                  value = 2025,
                                                  min = 2021,
                                                  max = 2050,
                                                  step = 1),
                                     p(" "),
                                     numericInput("horizon_year_2",
                                                  "Horizon Year 2:",
                                                  value = 2030,
                                                  min = 2021,
                                                  max = 2050,
                                                  step = 1),
                                     p(""),
                                     numericInput("horizon_year_3",
                                                  "Horizon Year 3:",
                                                  value = 2050,
                                                  min = 2021,
                                                  max = 2050,
                                                  step = 1),
                                     p(""),
                                     selectInput("transportation_scope",
                                                 "Transportation System Scope:",
                                                 c("All Roadways","NHS Only"),
                                                 "All Roadways"),
                                     p(""),
                                     selectInput("scope_emissions",
                                                 "Include Electricity",
                                                 c("Yes","No"),
                                                 "Yes"),
                                     p(""),
                                     selectInput("scope_fuels",
                                                 "Include Upstream Fuels",
                                                 c("Yes","No"),
                                                 "No"),
                                     bsTooltip("scope_fuels",
                                               "Upstream Fuels refer to emissions associated with the production, extraction, and transportation of liquid and gaseous fuels including gasoline, diesel and CPG.",
                                               "right",
                                               options = list(container = "body")),
                                     p(""),
                                     selectInput("vmt_forecast_input",
                                                 "VMT Forecast",
                                                 c("Default","Custom"),
                                                 "Default"),
                                     p(""),
                                     selectInput("ev_baseline_input",
                                                 "Vehicle Electrification Baseline",
                                                 c("AEO Baseline","ACC II","ACC II + ACT","Custom"),
                                                 "AEO Baseline"),
                                     p(""),
                                     numericInput("grid_emissions_input",
                                                  "Electricity Grid Emissions Net-Zero Year",
                                                  value = 2025,
                                                  min = 2021,
                                                  max = 2050,
                                                  step = 1)
                                     
                              )),
                  ),
                  nav_panel(title = "Projects",
                            fluidRow(
                              column(10,

                              #     h3("Bicycle and Pedestrian lane miles of new infrastructure"),
                              accordion(
                                accordion_panel(
                                  HTML('<span style ="font-size: 24px; font-weight: bold;">Bicycle and
           Pedestrian Lane Miles of New Infrastructure</span>'),
           "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
      tempor incididunt ut labore et dolore magna aliqua. Amet nulla facilisi
      morbi tempus iaculis urna id. Scelerisque in dictum non consectetur a
      erat. Cursus sit amet dictum sit amet justo donec enim diam. Egestas
      pretium aenean pharetra magna ac placerat vestibulum. Et tortor consequat
      id porta nibh venenatis cras sed felis. Facilisis magna etiam tempor
      orci eu lobortis elementum nibh. Leo vel fringilla est ullamcorper eget
      nulla. Habitasse platea dictumst quisque sagittis purus sit amet volutpat
      consequat. Justo nec ultrices dui sapien eget mi proin sed. Nulla
      facilisi nullam vehicula ipsum a arcu cursus vitae. Eu mi bibendum neque
      egestas congue quisque egestas. Ornare massa eget egestas purus viverra
      accumsan in nisl nisi. Risus sed vulputate odio ut enim. Sem nulla
      pharetra diam sit amet nisl. At urna condimentum mattis pellentesque id
      nibh tortor id. Nibh praesent tristique magna sit amet purus gravida
      quis blandit. Arcu cursus euismod quis viverra nibh cras pulvinar
      mattis. Elit sed vulputate mi sit amet. Id eu nisl nunc mi."
                                ),
      id = "acc1",
      open = FALSE
                              ),
                              ),
      column(2,
      actionButton("reset_bikeped_projs_tbl", "Reset Bike Ped Projects", class = "btn-custom"),
      ),
                            ),
      fluidRow(
      DT::dataTableOutput("bikeped_projs_tbl")

                  ),
#      fluidRow(),
      fluidRow(
        h3("Transit: Increased Fixed Route Service (new Vehicles Operating in Maximum Service)"),
        DT::dataTableOutput("transit_fixed_projs_tbl")
      ),
      fluidRow(
        h3("Transit: Increased Demand Response Service (new Vehicles Operating in Maximum Service)"),
        DT::dataTableOutput("transit_dr_projs_tbl")
      ),
      fluidRow(
        h3("Fleet Electrification (number of vehicles replaced)"),
        DT::dataTableOutput("transit_el_projs_tbl")
      ),
      fluidRow(
        h3("Public Transportation: Bus Priority Treatment (number of units)"),
        DT::dataTableOutput("transit_bus_projs_tbl")
      ),
      fluidRow(
        h3("Public Transportation: Rail (new Vehicles Operating in Maximum Service)"),
        DT::dataTableOutput("public_rail_projs_tbl")
      ),
      fluidRow(
        h3("Travel Demand Management (number of units)"),
        DT::dataTableOutput("tdm_projs_tbl")
      ),
      fluidRow(
        h3("Micromobility (number of units)"),
        DT::dataTableOutput("micro_projs_tbl")
      ),
      fluidRow(
        h3("Traffic Operations (number of intersection improvements)"),
        DT::dataTableOutput("traffic_ops_projs_tbl")
      ),
      fluidRow(
        h3("Medium- and Heavy-Duty Vehicle Replacement (number of Vehicles Replaced)"),
        DT::dataTableOutput("mhdev_projs_tbl")
      ),
      fluidRow(
        h3("Park & Ride (number of units)"),
        DT::dataTableOutput("pnr_projs_tbl")
      ),
      fluidRow(
        h3("EV Charging Infrastructure (number of units)"),
        DT::dataTableOutput("evsi_projs_tbl")
      ),
      fluidRow(
        h3("Freight Intermodal Facilities (number of new intermodal facilities)"),
        DT::dataTableOutput("freight_projs_tbl")
      ),
      fluidRow(
        h3("Roadway expansion (number of new lane-miles)"),
        DT::dataTableOutput("expansion_projs_tbl")
      ),
      
                  ),
      nav_panel(title = "Assumptions",
                fluidRow(
                  p(""),
                  h3("Bicycle and Pedestrian Data",
                     tooltip(
                       bsicons::bs_icon("info-circle",
                                        title = ""),
                       placement = "top",
                       "Increasing the prior drive mode share will result in a larger reduction in VMT reduction and CO2.")
                  ),
                  p(""),
                  DT::dataTableOutput("bikeped_assmps_tbl")
                ),
                fluidRow(
                  p(""),
                  h3("Transit Data"),
                  p(""),
                  DT::dataTableOutput("transit_assmps_tbl")
                ),
                fluidRow(
                  p(""),
                  h3("Travel Demand Management (TDM) Data"),
                  p(""),
                  DT::dataTableOutput("tdm_assmps_tbl")
                ),
                fluidRow(
                  p(""),
                  h3("Micromobility Data"),
                  p(""),
                  DT::dataTableOutput("micro_assmps_tbl")
                ),
                fluidRow(
                  p(""),
                  h3("Traffic operations & roadway expansion  Data"),
                  p(""),
                  DT::dataTableOutput("traffic_ops_assmps_tbl")
                ),
                fluidRow(
                  p(""),
                  h3("Medium & heavy-duty vehicle replacement Data"),
                  p(""),
                  DT::dataTableOutput("mhdv_assmps_tbl")
                ),
                fluidRow(
                  p(""),
                  h3("Park & Ride Data"),
                  p(""),
                  DT::dataTableOutput("pnr_assmps_tbl")
                ),
                fluidRow(
                  p(""),
                  h3("Electric Vehicle charging infrastructure Data"),
                  p(""),
                  DT::dataTableOutput("evsi_assmps_tbl")
                )
                
                
                
                
      ),
      nav_panel(title = "Costs",
                fluidRow(
                  p(""),
                  h3("Bicycle & Pedestrian"),
                  p(""),
                  DT::dataTableOutput("bikeped_costs_tbl")
                ),
                fluidRow(
                  p(""),
                  h3("Transit: Fixed Route Service"),
                  p(""),
                  DT::dataTableOutput("transit_fixed_costs_tbl")
                ),
                fluidRow(
                  p(""),
                  h3("Transit: Demand Response Service"),
                  p(""),
                  DT::dataTableOutput("transit_dr_costs_tbl")
                ),
                fluidRow(
                  p(""),
                  h3("Public Transportation: Bus Priority Treatment"),
                  p(""),
                  DT::dataTableOutput("pub_trans_priority_costs_tbl")
                ),
                fluidRow(
                  p(""),
                  h3("Public Transportation: Rail"),
                  p(""),
                  DT::dataTableOutput("pub_trans_rail_costs_tbl")
                ),
                fluidRow(
                  p(""),
                  h3("Travel Demand Management"),
                  p(""),
                  DT::dataTableOutput("tdm_costs_tbl")
                ),
                fluidRow(
                  p(""),
                  h3("Micromobility"),
                  p(""),
                  DT::dataTableOutput("micro_costs_tbl")
                ),
                fluidRow(
                  p(""),
                  h3("Traffic Operations - Intersection"),
                  p(""),
                  DT::dataTableOutput("traffic_ops_costs_tbl")
                ),
                fluidRow(
                  p(""),
                  h3("Medium and Heavy Duty Vehicle Replacement (per-vehicle cost)"),
                  p(""),
                  DT::dataTableOutput("mhdev_costs_tbl")
                ),
                fluidRow(
                  p(""),
                  h3("Park & Ride"),
                  p(""),
                  DT::dataTableOutput("pnr_costs_tbl")
                ),
                fluidRow(
                  p(""),
                  h3("EV Charging Infrastructure"),
                  p(""),
                  DT::dataTableOutput("evsi_costs_tbl")
                ),
                fluidRow(
                  p(""),
                  h3("Roadway Expansion"),
                  p(""),
                  DT::dataTableOutput("roadway_expand_costs_tbl")
                ),
                fluidRow(
                  p(""),
                  h3("Fuel Price (2022)"),
                  p(""),
                  DT::dataTableOutput("fuel_costs_tbl")
                ),
                fluidRow(
                  p(""),
                  h3("Intermodal Freight Investment"),
                  p(""),
                  DT::dataTableOutput("intermodal_costs_tbl")
                ),
      ),
      nav_panel(title = "Scenarios",
                fluidRow(
                  p(""),
                  h3("Scenario Testing"),
                  p(""),
                  DT::dataTableOutput("scenario_tbl")
                )
      ),
      nav_panel(title = "Advanced",
                
                fluidRow(
                  p(""),
                  h3("Custom Forecast: Percent of on-road vehicles that are EVs",
                     tooltip(
                       bsicons::bs_icon("info-circle",
                                        title = ""),
                       placement = "top",
                       "Enter values as a whole number (differently stated, type '55' in a cell to indicate '55%').")
                  ),
                  p(""),
                  DT::dataTableOutput("ev_forecast_sheet_tbl")
                ),
                
                fluidRow(
                  h3("Custom Forecast: Vehicles Miled Traveled (VMT)"),
                  DT::dataTableOutput("vmt_forecast_sheet_tbl")
                ),
                fluidRow(
                  h3("Onroad Public Transit - Fuel Technology Fraction"),
                  DT::dataTableOutput("onroad_fuel_tech_frac_sheet_tbl")
                ),
                fluidRow(
                  h3("Passenger Rail"),
                  DT::dataTableOutput("pass_rail_sheet_tbl")
                ),
                fluidRow(
                  h3("Freight Rail"),
                  DT::dataTableOutput("freight_rail_sheet_tbl")
                ),
                fluidRow(
                  h3("Construction and Maintenance"),
                  DT::dataTableOutput("construction_sheet_tbl")
                ),
                fluidRow(
                  h3("Fuel Apportionments"),
                  DT::dataTableOutput("fuel_apportionment_sheet_tbl")
                )
                
                
                
                
                
                
      )
                )),
      
      nav_panel(title = "Outputs",
                navset_card_pill(
                  placement = "above",
                  nav_panel(title = "Baseline GHG Forecast",
                            
                            h2("Baseline GHG Forecast"),
                            h3("Transportation GHG Forecast"),
                            
                            DT::dataTableOutput("baseline_outputs")
                            
                  ),
                  nav_panel(title = "Scenario and Strategy Summary",
                            fluidRow(
                              p(""),
                              title = "Select Indicator",
                              selectizeInput(inputId = "scenario_indicator",
                                             label = "Indicator",
                                             selected = 'em_mt_co2_change',
                                             choices = c( 
                                               'MT CO2e' = 'CO2',
                                               'VMT (Mile)' = 'VMT',
                                               'MT NOx' = 'Nox',
                                               'MT PM2.5' = 'PM2.5',
                                               'Daily Active Trips' = 'New Daily Active Trips')
                              )),
                            fluidRow(
                              column(6,
                                     DT::DTOutput('emission_change_tbl'),
                                     fluidRow(
                                       column(6,
                                              br(),
                                              downloadButton('downloadscenario_result', 'Download Results'))
                                     )),
                              column(6,
                                     plotlyOutput("emission_change_graph", width = "auto", height = "auto"))),
                  ),
                  nav_panel(title = "Cost effectiveness",
                            fluidRow(
                              p(""),
                              p("All results are reported in terms of annual change per $M investment."),
                              h3("Bicycle & Pedestrian"),
                              p(""),
                              DT::dataTableOutput("bikeped_costs_outputs_tbl")
                            ),
                            fluidRow(
                              p(""),
                              h3("Transit: Increased Fixed Route Service"),
                              p(""),
                              DT::dataTableOutput("transit_fixed_costs_outputs_tbl")
                            ),
                            fluidRow(
                              p(""),
                              h3("Transit: Increased Demand Response Service"),
                              p(""),
                              DT::dataTableOutput("transit_dr_costs_outputs_tbl")
                            ),
                            fluidRow(
                              p(""),
                              h3("Public Transportation: Bus Priority Treatment"),
                              p(""),
                              DT::dataTableOutput("pub_trans_priority_costs_outputs_tbl")
                            ),
                            fluidRow(
                              p(""),
                              h3("Transit: Fleet Electrification"),
                              p(""),
                              DT::dataTableOutput("transit_zeb_costs_outputs_tbl")
                            ),
                            fluidRow(
                              p(""),
                              h3("Public Transportation: Rail"),
                              p(""),
                              DT::dataTableOutput("pub_trans_rail_costs_outputs_tbl")
                            ),
                            fluidRow(
                              p(""),
                              h3("Travel Demand Management"),
                              p(""),
                              DT::dataTableOutput("tdm_costs_outputs_tbl")
                            ),
                            fluidRow(
                              p(""),
                              h3("Micromobility"),
                              p(""),
                              DT::dataTableOutput("micro_costs_outputs_tbl")
                            ),
                            fluidRow(
                              p(""),
                              h3("Traffic Operations: Intersections"),
                              p(""),
                              DT::dataTableOutput("traffic_ops_costs_outputs_tbl")
                            ),
                            fluidRow(
                              p(""),
                              h3("Medium and Heavy Duty Vehicle Replacement (Electrification)"),
                              p(""),
                              DT::dataTableOutput("mhdev_costs_outputs_tbl")
                            ),
                            fluidRow(
                              p(""),
                              h3("Park & Ride"),
                              p(""),
                              DT::dataTableOutput("pnr_costs_outputs_tbl")
                            ),
                            fluidRow(
                              p(""),
                              h3("EV Charging Infrastructure"),
                              p(""),
                              DT::dataTableOutput("evsi_costs_outputs_tbl")
                            ),
                            fluidRow(
                              p(""),
                              h3("Roadway Expansion"),
                              p(""),
                              DT::dataTableOutput("roadway_expand_costs_outputs_tbl")
                            ),
                            fluidRow(
                              p(""),
                              h3("Intermodal Freight Investment"),
                              p(""),
                              DT::dataTableOutput("intermodal_costs_outputs_tbl")
                            )
                  ),
                )),
      nav_panel(title = "Sources",
                h2("Sources"),
                p("The following resources were used in developing the TEA-CART tool."),
                
                DT::dataTableOutput("source_table")
      ),
      nav_spacer(),
      nav_menu(
        title = tags$img(src = "GCC_Logo_Transparent_Stacked.png", height = "30px"),
        nav_item(tags$a("Visit", href = "https://www.georgetownclimate.org/", target = "_blank")))
      
      
    )
    
  )
  
}

# setting themes - golem probably wants them somewhere else
# enabling thematic
thematic::thematic_shiny(font = "auto")

# setting default ggplot theme
theme_set(theme_bw(base_size = 16))

# https://stackoverflow.com/questions/31013769/locking-r-shiny-dashboard-sidebar-shinydashboard
# https://rstudio.github.io/bslib/articles/sidebars/index.html


# Start Server Function ---------------------------------------------------

server <- function(input, output, session) {
  #Source Local Scripts --------------------------------------------------------
  source("functions/render_custom_datatable_SLVER.R", local = T)
  source("functions/reshaping.R", local = T)
  
  #set reactiveValues ----------------------------------------------------------
  
  rv <- reactiveValues()
  rvs <- read_user_inputs_version2(".\\data\\2.User_Inputs.xlsx")
  
  # Initiate or Upload User Inputs -------------------------------------------
  
  observeEvent(input$user_inputs_upload, {
    if(isTruthy(input$user_inputs_upload)){
      user_inputs <- read_user_inputs_excel(input$user_inputs_upload$datapath)
    } else{
      user_inputs <- read_user_inputs_excel(".\\data\\2.User_Inputs.xlsx")
    }
    
    # Assign each table in user_inputs to rv
    for(name in names(user_inputs)) {
      rv[[name]] <- user_inputs[[name]]
    }
  }, ignoreNULL = F, ignoreInit = F)

  # ## Example of how to modify the reactiveValues
  # observeEvent(rv$Capital_Project_Inputs, { ### may be good to use observe instead
  #   # browser()
  #   rv$random_calculated_table <- rv$Capital_Project_Inputs %>% filter(value == 4)
  #   print(rv$random_calculated_table)
  # })
  
  # Download user inputs -------------------------------------------------------
  ### will eventually use openxlsx to format the excel file to match the uploaded file exactly
  output$user_inputs_download <- downloadHandler(
    filename = function() {
      paste0(".\\data\\2.User_Inputs_", format(Sys.time(), "%H:%M"), ".xlsx")
    },
    content = function(file) {
      
      # browser()
      return(openxlsx::write.xlsx(x = list("Costs" = rvs$Costs,
                                           "Baseline" = rvs$Baseline,
                                           "Projects" = rvs$Projects), 
                           file = file))
    }
  )
  
  # server sources ---------------------------------------------------
  
  sources_data <- read_xlsx(".\\data\\sources.xlsx", sheet = 1, col_names = TRUE)
  
  output$source_table <- renderDT({
    DT::datatable(sources_data,
                  escape = FALSE,
                  options = list(pageLength = 10,
                                 autoWidth = FALSE,
                                 buttons = c('csv', 'excel')
                  ),
                  extensions = 'Buttons',
                  filter = 'bottom',
                  rownames = FALSE)
  })
  
  # server project inputs ------------------------------------------------------
  
  projects_names <- c("bikeped_projs",
                      "transit_fixed_projs",
                      "transit_dr_projs",
                      "transit_el_projs",
                      "transit_bus_projs",
                      "public_rail_projs",
                      "tdm_projs",
                      "micro_projs",
                      "traffic_ops_projs",
                      "mhdev_projs",
                      "pnr_projs",
                      "evsi_projs",
                      "freight_projs",
                      "expansion_projs")
  
  read_static_tables(".\\data\\projects.xlsx", projects_names)
  
  
  #create project tables -----------------------------------------------------------
  
  # rendering bike ped table

  output$bikeped_projs_tbl <- renderDT({
    req(rvs$Projects)
    temp_send <- rvs$Projects

    render_custom_datatable_SLVER(
      data_reactive = temp_send,
      table_number = 1,
      non_editable_cols = c(0, 1, 2),
      page_length = 19,
      comma_rows = 0:19,
      percent_rows = integer(0),
      currency_rows = integer(0),
      decimal_rows = integer(0))
    
  })
  

  output$transit_fixed_projs_tbl <- renderDT({
    
    req(rvs$Projects)
    temp_send <- rvs$Projects
    
    render_custom_datatable_SLVER(
    data_reactive = temp_send,
    table_number = 2,
    non_editable_cols = c(0, 1, 2, 3),
    page_length = 10,
    comma_rows = 0:6,
    percent_rows = integer(0),
    currency_rows = integer(0),
    decimal_rows = integer(0))
    
    })
  
  output$transit_dr_projs_tbl <- renderDT({
    
    req(rvs$Projects)
    temp_send <- rvs$Projects
    
    render_custom_datatable_SLVER(
      data_reactive = temp_send,
      table_number = 3,
      non_editable_cols = c(0, 1, 2, 3),
      page_length = 10,
      comma_rows = 0:6,
      percent_rows = integer(0),
      currency_rows = integer(0),
      decimal_rows = integer(0))

  })
  
  output$transit_el_projs_tbl <- renderDT({
    
    req(rvs$Projects)
    temp_send <- rvs$Projects
    
    render_custom_datatable_SLVER(
      data_reactive = temp_send,
      table_number = 4,
      non_editable_cols = c(0, 1, 2, 3),
      page_length = 10,
      comma_rows = 0:8,
      percent_rows = integer(0),
      currency_rows = integer(0),
      decimal_rows = integer(0))
    
  })
  
  output$transit_bus_projs_tbl <- renderDT({
    
    req(rvs$Projects)
    temp_send <- rvs$Projects
    
    render_custom_datatable_SLVER(
      data_reactive = temp_send,
      table_number = 5,
      non_editable_cols = c(0),
      page_length = 4,
      comma_rows = 0,
      percent_rows = integer(0),
      currency_rows = integer(0),
      decimal_rows = integer(0))
    
  })
  
  output$public_rail_projs_tbl <- renderDT({
    
    req(rvs$Projects)
    temp_send <- rvs$Projects
    
    render_custom_datatable_SLVER(
      data_reactive = temp_send,
      table_number = 6,
      non_editable_cols = c(0,1,2),
      page_length = 8,
      comma_rows = 0:3,
      percent_rows = integer(0),
      currency_rows = integer(0),
      decimal_rows = integer(0))
    
  })
  
  output$tdm_projs_tbl <- renderDT({
    
    req(rvs$Projects)
    temp_send <- rvs$Projects
    
    render_custom_datatable_SLVER(
      data_reactive = temp_send,
      table_number = 7,
      non_editable_cols = c(0),
      page_length = 10,
      comma_rows = 0,
      percent_rows = integer(0),
      currency_rows = integer(0),
      decimal_rows = integer(0))
    
  })
  
  output$micro_projs_tbl <- renderDT({
    
    req(rvs$Projects)
    temp_send <- rvs$Projects
    
    render_custom_datatable_SLVER(
      data_reactive = temp_send,
      table_number = 8,
      non_editable_cols = c(0),
      page_length = 10,
      comma_rows = 0,
      percent_rows = integer(0),
      currency_rows = integer(0),
      decimal_rows = integer(0))
    
  })
  
  output$traffic_ops_projs_tbl <- renderDT({
    
    req(rvs$Projects)
    temp_send <- rvs$Projects
    
    render_custom_datatable_SLVER(
      data_reactive = temp_send,
      table_number = 9,
      non_editable_cols = c(0,1,2),
      page_length = 10,
      comma_rows = 0:3,
      percent_rows = integer(0),
      currency_rows = integer(0),
      decimal_rows = integer(0))
    
  })
  
  output$mhdev_projs_tbl <- renderDT({
    
    req(rvs$Projects)
    temp_send <- rvs$Projects
    
    render_custom_datatable_SLVER(
      data_reactive = temp_send,
      table_number = 10,
      non_editable_cols = c(0,1,2),
      page_length = 10,
      comma_rows = 0:4,
      percent_rows = integer(0),
      currency_rows = integer(0),
      decimal_rows = integer(0))
    
  })
  
  output$pnr_projs_tbl <- renderDT({
    
    req(rvs$Projects)
    temp_send <- rvs$Projects
    
    render_custom_datatable_SLVER(
      data_reactive = temp_send,
      table_number = 11,
      non_editable_cols = c(0,1),
      page_length = 1,
      comma_rows = 0,
      percent_rows = integer(0),
      currency_rows = integer(0),
      decimal_rows = integer(0))
    
  })
  
  output$evsi_projs_tbl <- renderDT({
    
    req(rvs$Projects)
    temp_send <- rvs$Projects
    
    render_custom_datatable_SLVER(
      data_reactive = temp_send,
      table_number = 12,
      non_editable_cols = c(0,1),
      page_length = 10,
      comma_rows = 0:4,
      percent_rows = integer(0),
      currency_rows = integer(0),
      decimal_rows = integer(0))
    
  })
  
  output$freight_projs_tbl <- renderDT({
    
    req(rvs$Projects)
    temp_send <- rvs$Projects
    
    render_custom_datatable_SLVER(
      data_reactive = temp_send,
      table_number = 13,
      non_editable_cols = c(0),
      page_length = 10,
      comma_rows = 0:4,
      percent_rows = integer(0),
      currency_rows = integer(0),
      decimal_rows = integer(0))
    
  })
  
  output$expansion_projs_tbl <- renderDT({
    
    req(rvs$Projects)
    temp_send <- rvs$Projects
    
    render_custom_datatable_SLVER(
      data_reactive = temp_send,
      table_number = 14,
      non_editable_cols = c(0,1,2),
      page_length = 10,
      comma_rows = 0:4,
      percent_rows = integer(0),
      currency_rows = integer(0),
      decimal_rows = integer(0))
    
  })

# Observe Table Edits ---------------------------------------------------------

    # observe edits to the bikeped_projs
  observeEvent(input$bikeped_projs_tbl_cell_edit, {
    req(rvs$Projects)
    
    rvs$Projects[rvs$Projects$table_no_ui == 1,] <- reshaping_projects(input$bikeped_projs_tbl_cell_edit,
                                                                       rvs$Projects,
                                                                       tbl_no = 1,
                                                                       col1 = 'area_type',
                                                                       col2 = 'facility_type',
                                                                       col3 = 'unit',
                                                                       input$horizon_year_1,
                                                                       input$horizon_year_2,
                                                                       input$horizon_year_3)
  })
  
  # observe edits to the transit_fixed_projs
  observeEvent(input$transit_fixed_projs_tbl_cell_edit, {
    req(rvs$Projects)

    rvs$Projects[rvs$Projects$table_no_ui == 2,] <- reshaping_projects(input$transit_fixed_projs_tbl_cell_edit,
                                                              rvs$Projects,
                                                              tbl_no = 2,
                                                              col1 = 'area_type',
                                                              col2 = 'fuel_type',
                                                              col3 = 'transit_mode',
                                                              col4 = 'unit',
                                                              input$horizon_year_1,
                                                              input$horizon_year_2,
                                                              input$horizon_year_3)
    })
  
  # observe edits to the transit_dr_projs_tbl_cell_edit
  observeEvent(input$transit_dr_projs_tbl_cell_edit, {
    req(rvs$Projects)
    
    rvs$Projects[rvs$Projects$table_no_ui == 3,] <- reshaping_projects(input$transit_dr_projs_tbl_cell_edit,
                                                              rvs$Projects,
                                                              tbl_no = 3,
                                                              col1 = 'area_type',
                                                              col2 = 'fuel_type',
                                                              col3 = 'transit_mode',
                                                              col4 = 'unit',
                                                              input$horizon_year_1,
                                                              input$horizon_year_2,
                                                              input$horizon_year_3)
  })
  
  # observe edits to the transit_el_projs_tbl
  observeEvent(input$transit_el_projs_tbl_cell_edit, {
    req(rvs$Projects)
    
    rvs$Projects[rvs$Projects$table_no_ui == 4,] <- reshaping_projects(input$transit_el_projs_tbl_cell_edit,
                                                              rvs$Projects,
                                                              tbl_no = 4,
                                                              col1 = 'area_type',
                                                              col2 = 'fuel_type',
                                                              col3 = 'transit_mode',
                                                              col4 = 'unit',
                                                              input$horizon_year_1,
                                                              input$horizon_year_2,
                                                              input$horizon_year_3)
  })
  
  # observe edits to the transit_bus_projs_tbl  
  observeEvent(input$transit_bus_projs_tbl_cell_edit, {

    rvs$Projects[rvs$Projects$table_no_ui == 5,] <- reshaping_projects(input$transit_bus_projs_tbl_cell_edit,
                                                              rvs$Projects,
                                                              tbl_no = 5,
                                                              col1 = 'unit',
                                                              input$horizon_year_1,
                                                              input$horizon_year_2,
                                                              input$horizon_year_3)
    
    
    #updated_table[user_data$row,"value"] <- as.numeric(user_data$value)
    
  })
  
  # observe edits to the public_rail_projs table
  observeEvent(input$public_rail_projs_tbl_cell_edit, {
    
    rvs$Projects[rvs$Projects$table_no_ui == 6,] <- reshaping_projects(input$public_rail_projs_tbl_cell_edit,
                                                              rvs$Projects,
                                                              tbl_no = 6,
                                                              col1 = 'fuel_type',
                                                              col2 = 'transit_mode',
                                                              col3 = 'unit',
                                                              input$horizon_year_1,
                                                              input$horizon_year_2,
                                                              input$horizon_year_3)
    
    
    #updated_table[user_data$row,"value"] <- as.numeric(user_data$value)
    
  })
  
  # observe edits to the tdm_projs_tbl table
  observeEvent(input$tdm_projs_tbl_cell_edit, {

    rvs$Projects[rvs$Projects$table_no_ui == 7,] <- reshaping_projects(input$tdm_projs_tbl_cell_edit,
                                                              rvs$Projects,
                                                              tbl_no = 7,
                                                              col1 = 'unit',
                                                              input$horizon_year_1,
                                                              input$horizon_year_2,
                                                              input$horizon_year_3)


    #updated_table[user_data$row,"value"] <- as.numeric(user_data$value)

  })
  
  # observe edits to the micro_projs_tbl table
  observeEvent(input$micro_projs_tbl_cell_edit, {
    
    rvs$Projects[rvs$Projects$table_no_ui == 8,] <- reshaping_projects(input$micro_projs_tbl_cell_edit,
                                                              rvs$Projects,
                                                              tbl_no = 8,
                                                              col1 = 'unit',
                                                              input$horizon_year_1,
                                                              input$horizon_year_2,
                                                              input$horizon_year_3)
    
    
    #updated_table[user_data$row,"value"] <- as.numeric(user_data$value)
    
  })
  
  # observe edits to the traffic_ops_projs_tbl table
  observeEvent(input$traffic_ops_projs_tbl_cell_edit, {
    
    rvs$Projects[rvs$Projects$table_no_ui == 9,] <- reshaping_projects(input$traffic_ops_projs_tbl_cell_edit,
                                                              rvs$Projects,
                                                              tbl_no = 9,
                                                              col1 = 'area_type',
                                                              col2 = 'road_class',
                                                              col3 = 'unit',
                                                              input$horizon_year_1,
                                                              input$horizon_year_2,
                                                              input$horizon_year_3)
    
    
    #updated_table[user_data$row,"value"] <- as.numeric(user_data$value)
    
  })
  
  # observe edits to the mhdev_projs_tbl table
  observeEvent(input$mhdev_projs_tbl_cell_edit, {
    
    rvs$Projects[rvs$Projects$table_no_ui == 10,] <- reshaping_projects(input$mhdev_projs_tbl_cell_edit,
                                                              rvs$Projects,
                                                              tbl_no = 10,
                                                              col1 = 'veh_type',
                                                              col2 = 'fuel_type',
                                                              col3 = 'unit',
                                                              input$horizon_year_1,
                                                              input$horizon_year_2,
                                                              input$horizon_year_3)
    
    
    #updated_table[user_data$row,"value"] <- as.numeric(user_data$value)
    
  })
  
  # observe edits to the mhdev_projs_tbl table
  observeEvent(input$pnr_projs_tbl_cell_edit, {
    
    rvs$Projects[rvs$Projects$table_no_ui == 11,] <- reshaping_projects(input$pnr_projs_tbl_cell_edit,
                                                               rvs$Projects,
                                                               tbl_no = 11,
                                                               col1 = 'unit',
                                                               input$horizon_year_1,
                                                               input$horizon_year_2,
                                                               input$horizon_year_3)
    
    
    #updated_table[user_data$row,"value"] <- as.numeric(user_data$value)
    
  })
  
  # observe edits to the evsi_projs_tbl table
  observeEvent(input$evsi_projs_tbl_cell_edit, {
    
    rvs$Projects[rvs$Projects$table_no_ui == 12,] <- reshaping_projects(input$evsi_projs_tbl_cell_edit,
                                                               rvs$Projects,
                                                               tbl_no = 12,
                                                               col1 = 'charge_port_detail',
                                                               col2 = 'unit',
                                                               input$horizon_year_1,
                                                               input$horizon_year_2,
                                                               input$horizon_year_3)
    
    
    #updated_table[user_data$row,"value"] <- as.numeric(user_data$value)
    
  })
  
  # observe edits to the freight_projs_tbl table
  observeEvent(input$freight_projs_tbl_cell_edit, {
    
    rvs$Projects[rvs$Projects$table_no_ui == 13,] <- reshaping_projects(input$freight_projs_tbl_cell_edit,
                                                               rvs$Projects,
                                                               tbl_no = 13,
                                                               col1 = 'unit',
                                                               input$horizon_year_1,
                                                               input$horizon_year_2,
                                                               input$horizon_year_3)
    
    
    #updated_table[user_data$row,"value"] <- as.numeric(user_data$value)
    
  })
  # observe edits to the expansion_projs_tbl table
  observeEvent(input$expansion_projs_tbl_cell_edit, {
    
    rvs$Projects[rvs$Projects$table_no_ui == 14,] <- reshaping_projects(input$expansion_projs_tbl_cell_edit,
                                                               rvs$Projects,
                                                               tbl_no = 14,
                                                               col1 = 'area_type',
                                                               col2 = 'road_class',
                                                               col3 = 'unit',
                                                               input$horizon_year_1,
                                                               input$horizon_year_2,
                                                               input$horizon_year_3)
    
    
    #updated_table[user_data$row,"value"] <- as.numeric(user_data$value)
    
  })


# observe reset buttons ---------------------------------------------------


  # Observe reset bike ped projects button
  observeEvent(input$reset_bikeped_projs_tbl, {
    
    rvs$Projects[rvs$Projects$table_no_ui == 1,] <- initial_projects[initial_projects$table_no_ui == 1, ]

  })  
  
  
  # projects_names <- c("bikeped_projs",
  #                     "transit_fixed_projs",
  #                     "transit_dr_projs",
  #                     "transit_el_projs",
  #                     "transit_bus_projs",
  #                     "public_rail_projs",
  #                     "tdm_projs",
  #                     "micro_projs",
  #                     "traffic_ops_projs",
  #                     "mhdev_projs",
  #                     "pnr_projs",
  #                     "evsi_projs",
  #                     "freight_projs",
  #                     "expansion_projs")

  # server assumptions ------------------------------------------------------
  
  assumptions_names <- c("bikeped_assmps",
                         "transit_assmps",
                         "tdm_assmps",
                         "micro_assmps",
                         "traffic_ops_assmps",
                         "mhdv_assmps",
                         "pnr_assmps",
                         "evsi_assmps")
  
  
  read_static_tables(".\\data\\assumptions.xlsx", assumptions_names)
  
  
  ## create assumption tables -----------------------------------------------------------
  

  output$bikeped_assmps_tbl <- renderDT({
    req(rvs$Assumptions)
    
    render_custom_datatable_SLVER(
    data_reactive = rvs$Assumptions,
    table_number = 1,
    is_year_table = FALSE,
    non_editable_cols = c(0, 1),
    page_length = 10,
    comma_rows = integer(0),
    percent_rows = integer(0),
    currency_rows = integer(0),
    decimal_rows = 2:7)
  })
  
  
  output$transit_assmps_tbl <- renderDT({
    req(rvs$Assumptions)
    
    render_custom_datatable_SLVER(
      data_reactive = rvs$Assumptions,
      table_number = 2,
      is_year_table = FALSE,
      non_editable_cols = c(0, 1),
      page_length = 10,
      comma_rows = c(18, 47),
      percent_rows = integer(0),
      currency_rows = integer(0),
      decimal_rows = c(0:17,19:46))
  })
  
  
  output$tdm_assmps_tbl <- renderDT({
    req(rvs$Assumptions)
    
    render_custom_datatable_SLVER(
      data_reactive = rvs$Assumptions,
      table_number = 3,
      is_year_table = FALSE,
      non_editable_cols = c(0, 1),
      page_length = 10,
      comma_rows = integer(0),
      percent_rows = integer(0),
      currency_rows = integer(0),
      decimal_rows = c(0:2))
  })
  
  
  output$micro_assmps_tbl <- renderDT({
    req(rvs$Assumptions)
    
    render_custom_datatable_SLVER(
      data_reactive = rvs$Assumptions,
      table_number = 4,
      is_year_table = FALSE,
      non_editable_cols = c(0, 1),
      page_length = 10,
      comma_rows = integer(0),
      percent_rows = integer(0),
      currency_rows = integer(0),
      decimal_rows = c(0:4))
  })
  
  
  output$traffic_ops_assmps_tbl <- renderDT({
    req(rvs$Assumptions)
    
    render_custom_datatable_SLVER(
      data_reactive = rvs$Assumptions,
      table_number = 5,
      is_year_table = FALSE,
      non_editable_cols = c(0, 1),
      page_length = 10,
      comma_rows = integer(0),
      percent_rows = integer(0),
      currency_rows = integer(0),
      decimal_rows = c(0:15))
  })
  
  
  output$mhdv_assmps_tbl <- renderDT({
    req(rvs$Assumptions)
    
    render_custom_datatable_SLVER(
      data_reactive = rvs$Assumptions,
      table_number = 6,
      is_year_table = FALSE,
      non_editable_cols = c(0, 1),
      page_length = 10,
      comma_rows = integer(0),
      percent_rows = integer(0),
      currency_rows = integer(0),
      decimal_rows = c(0:15))
  })
  
  
  output$pnr_assmps_tbl <- renderDT({
    req(rvs$Assumptions)
    
    render_custom_datatable_SLVER(
      data_reactive = rvs$Assumptions,
      table_number = 7,
      is_year_table = FALSE,
      non_editable_cols = c(0, 1),
      page_length = 10,
      comma_rows = integer(0),
      percent_rows = integer(0),
      currency_rows = integer(0),
      decimal_rows = c(0:15))
  })
  
  
  output$evsi_assmps_tbl <- renderDT({
    req(rvs$Assumptions)
    
    render_custom_datatable_SLVER(
      data_reactive = rvs$Assumptions,
      table_number = 8,
      is_year_table = FALSE,
      non_editable_cols = c(0, 1),
      page_length = 10,
      comma_rows = integer(0),
      percent_rows = integer(0),
      currency_rows = integer(0),
      decimal_rows = c(0:15))
  })
  
  
  ## make tables editable ----------------------------------------------------
  
  
  observeEvent(input$bikeped_assmps_edit, {
    bikeped_assmps <<- editData(bikeped_assmps, input$bikeped_assmps_edit, 'bikeped_assmps_tbl')
  })
  
  observeEvent(input$transit_assmps_edit, {
    transit_assmps <<- editData(transit_assmps, input$transit_assmps_edit, 'transit_assmps_tbl')
  })
  
  observeEvent(input$tdm_assmps_edit, {
    tdm_assmps <<- editData(tdm_assmps, input$tdm_assmps_edit, 'tdm_assmps_tbl')
  })
  
  observeEvent(input$micro_assmps_edit, {
    micro_assmps <<- editData(micro_assmps, input$micro_assmps_edit, 'micro_assmps_tbl')
  })
  
  observeEvent(input$traffic_ops_assmps_edit, {
    traffic_ops_assmps <<- editData(traffic_ops_assmps, input$traffic_ops_assmps_edit, 'traffic_ops_assmps_tbl')
  })
  
  observeEvent(input$mhdv_assmps_edit, {
    mhdv_assmps <<- editData(mhdv_assmps, input$mhdv_assmps_edit, 'mhdv_assmps_tbl')
  })
  
  observeEvent(input$pnr_assmps_edit, {
    pnr_assmps <<- editData(pnr_assmps, input$pnr_assmps_edit, 'pnr_assmps_tbl')
  })
  
  observeEvent(input$evsi_assmps_edit, {
    evsi_assmps <<- editData(evsi_assmps, input$evsi_assmps_edit, 'evsi_assmps_tbl')
  })
  
  
  
  # costs inputs server ------------------------------------------------------------
  
  
  costs_names <- c("bikeped_costs",
                   "transit_fixed_costs",
                   "transit_dr_costs",
                   "pub_trans_priority_costs",
                   "tdm_costs",
                   "pub_trans_rail_costs",
                   "micro_costs",
                   "traffic_ops_costs",
                   "mhdev_costs",
                   "pnr_costs",
                   "evsi_costs",
                   "roadway_expand_costs",
                   "fuel_costs",
                   "intermodal_costs")
  
  read_static_tables(".\\data\\costs_inputs.xlsx", costs_names)
  
  
  ## create tables -----------------------------------------------------------
  
  output$bikeped_costs_tbl <- create_table(bikeped_costs,
                                           list(target = 'row',
                                                disable = list(columns = c(0,1)),
                                                autoWidth = TRUE))
  
  output$transit_fixed_costs_tbl <- create_table(transit_fixed_costs,
                                                 list(target = 'row',
                                                      disable = list(columns = c(0,1)),
                                                      autoWidth = TRUE))
  
  output$transit_dr_costs_tbl <- create_table(transit_dr_costs,
                                              list(target = 'row',
                                                   disable = list(columns = c(0,1)),
                                                   autoWidth = TRUE))
  
  output$pub_trans_priority_costs_tbl <- create_table(pub_trans_priority_costs,
                                                      list(target = 'row',
                                                           disable = list(columns = c(0,1)),
                                                           autoWidth = TRUE))
  
  output$pub_trans_rail_costs_tbl <- create_table(pub_trans_rail_costs,
                                                  list(target = 'row',
                                                       disable = list(columns = c(0,1)),
                                                       autoWidth = TRUE))
  
  output$tdm_costs_tbl <- create_table(tdm_costs,
                                       list(target = 'row',
                                            disable = list(columns = c(0,1)),
                                            autoWidth = TRUE))
  
  output$micro_costs_tbl <- create_table(micro_costs,
                                         list(target = 'row',
                                              disable = list(columns = c(0,1)),
                                              autoWidth = TRUE))
  
  output$traffic_ops_costs_tbl <- create_table(traffic_ops_costs,
                                               list(target = 'row',
                                                    disable = list(columns = c(0,1)),
                                                    autoWidth = TRUE))
  
  output$mhdev_costs_tbl <- create_table(mhdev_costs,
                                         list(target = 'row',
                                              disable = list(columns = c(0,1)),
                                              autoWidth = TRUE))
  
  output$pnr_costs_tbl <- create_table(pnr_costs,
                                       list(target = 'row',
                                            disable = list(columns = c(0,1)),
                                            autoWidth = TRUE))
  
  output$evsi_costs_tbl <- create_table(evsi_costs,
                                        list(target = 'row',
                                             disable = list(columns = c(0,1)),
                                             autoWidth = TRUE))
  
  output$roadway_expand_costs_tbl <- create_table(roadway_expand_costs,
                                                  list(target = 'row',
                                                       disable = list(columns = c(0,1)),
                                                       autoWidth = TRUE))
  
  output$fuel_costs_tbl <- create_table(fuel_costs,
                                        list(target = 'row',
                                             disable = list(columns = c(0,1)),
                                             autoWidth = TRUE))
  
  output$intermodal_costs_tbl <- create_table(intermodal_costs,
                                              list(target = 'row',
                                                   disable = list(columns = c(0,1)),
                                                   autoWidth = TRUE))
  
  
  ## make editable -----------------------------------------------------------
  
  observeEvent(input$bikeped_costs_edit, {
    bikeped_costs <<- editData(bikeped_costs, input$bikeped_costs_edit, 'bikeped_costs_tbl')
  })
  
  observeEvent(input$transit_fixed_costs_edit, {
    transit_fixed_costs <<- editData(transit_fixed_costs, input$transit_fixed_costs_edit, 'transit_fixed_costs_tbl')
  })
  
  observeEvent(input$transit_dr_costs_edit, {
    transit_dr_costs <<- editData(transit_dr_costs, input$transit_dr_costs_edit, 'transit_dr_costs_tbl')
  })
  
  observeEvent(input$pub_trans_priority_costs_edit, {
    pub_trans_priority_costs <<- editData(pub_trans_priority_costs, input$pub_trans_priority_costs_edit, 'pub_trans_priority_costs_tbl')
  })
  
  observeEvent(input$pub_trans_rail_costs_edit, {
    pub_trans_rail_costs <<- editData(pub_trans_rail_costs, input$pub_trans_rail_costs_edit, 'pub_trans_rail_costs_tbl')
  })
  
  observeEvent(input$tdm_costs_edit, {
    tdm_costs <<- editData(tdm_costs, input$tdm_costs_edit, 'tdm_costs_tbl')
  })
  
  observeEvent(input$micro_costs_edit, {
    micro_costs <<- editData(micro_costs, input$micro_costs_edit, 'micro_costs_tbl')
  })
  
  observeEvent(input$traffic_ops_costs_edit, {
    traffic_ops_costs <<- editData(traffic_ops_costs, input$traffic_ops_costs_edit, 'traffic_ops_costs_tbl')
  })
  
  observeEvent(input$mhdev_costs_edit, {
    mhdev_costs <<- editData(mhdev_costs, input$mhdev_costs_edit, 'mhdev_costs_tbl')
  })
  
  observeEvent(input$pnr_costs_edit, {
    pnr_costs <<- editData(pnr_costs, input$pnr_costs_edit, 'pnr_costs_tbl')
  })
  
  observeEvent(input$evsi_costs_edit, {
    evsi_costs <<- editData(evsi_costs, input$evsi_costs_edit, 'evsi_costs_tbl')
  })
  
  observeEvent(input$roadway_expand_costs_edit, {
    roadway_expand_costs <<- editData(roadway_expand_costs, input$roadway_expand_costs_edit, 'roadway_expand_costs_tbl')
  })
  
  observeEvent(input$fuel_costs_edit, {
    fuel_costs <<- editData(fuel_costs, input$fuel_costs_edit, 'fuel_costs_tbl')
  })
  
  observeEvent(input$intermodal_costs_edit, {
    intermodal_costs <<- editData(intermodal_costs, input$intermodal_costs_edit, 'intermodal_costs_tbl')
  })
  
  
  
  # server scenarios inputs -------------------------------------------------
  
  
  strategy_names <- c("Bicycle and Pedestrian",
                      "Transit Service Expansion",
                      "Micromobility",
                      "Travel Demand Management",
                      "Park and Ride",
                      "Transit Electrification",
                      "MD/HD Truck Replacement",
                      "Electric Vehicle Charging Infra.",
                      "Intermodal Freight Investment",
                      "Traffic Operations",
                      "Roadway Expansion",
                      "Custom Projects")
  
  rowName <- function(scenario) {
    as.character(
      checkboxInput(paste0("row", gsub(" ", "", scenario)), label = scenario)
    )
  }
  rowNames <- vapply(strategy_names, rowName, character(1))
  
  dat <- data.frame(
    vapply(strategy_names, function(scenario){
      as.character(
        checkboxInput(paste0("col1-", gsub(" ", "", scenario)), label = NULL)
      )
    }, character(1)),
    vapply(strategy_names, function(scenario){
      as.character(
        checkboxInput(paste0("col2-", gsub(" ", "", scenario)), label = NULL)
      )
    }, character(1))
  )
  
  names(dat) <- c(
    as.character(checkboxInput("col1", label = "Scenario 1")),
    as.character(checkboxInput("col2", label = "Scenario 2"))
  )
  
  rownames(dat) <- rowNames
  
  output$scenario_tbl <- renderDT({
    datatable(
      dat,
      escape = FALSE,
      select = "none",
      options = list(
        columnDefs = list(list(targets = c(1, 2),
                               orderable = FALSE,
                               className = "dt-center")
        ),
        pageLength = 12,
        initComplete = JS(
          "function() {",
          "  $('#col1').on('click', function(){",
          "    var cboxes = $('[id^=col1-]');",
          "    var checked = $('#col1').is(':checked');",
          "    cboxes.each(function(i, cbox) {",
          "      $(cbox).prop('checked', checked);",
          "    });",
          "  });",
          "  $('#col2').on('click', function(){",
          "    var cboxes = $('[id^=col2-]');",
          "    var checked = $('#col2').is(':checked');",
          "    cboxes.each(function(i, cbox) {",
          "      $(cbox).prop('checked', checked);",
          "    });",
          "  });",
          paste(
            sapply(strategy_names, function(scenario) {
              scenarioId <- gsub(" ", "", scenario)
              sprintf(
                "  $('#row%s').on('click', function(){\n    var cboxes = $('[id$=\\'-%s\\']');\n    var checked = $('#row%s').is(':checked');\n    cboxes.each(function(i, cbox) {\n      $(cbox).prop('checked', checked);\n    });\n  });",
                scenarioId, scenarioId, scenarioId
              )
            }),
            collapse = "\n"
          ),
          "}"
        ),
        preDrawCallback =
          JS('function() { Shiny.unbindAll(this.api().table().node()); }'),
        drawCallback =
          JS('function() { Shiny.bindAll(this.api().table().node()); } ')
      )
    )
  })
  
  
  
  # server advanced inputs ---------------------------------------------------------
  
  advanced_names <- c("ev_forecast_sheet",
                      "vmt_forecast_sheet",
                      "onroad_fuel_tech_frac_sheet",
                      "pass_rail_sheet",
                      "freight_rail_sheet",
                      "construction_sheet",
                      "fuel_apportionment_sheet")
  
  read_static_tables(".\\data\\advanced.xlsx", advanced_names)
  
  
  ## create tables -----------------------------------------------------------
  
  output$ev_forecast_sheet_tbl <- create_table(ev_forecast_sheet,
                                               list(target = 'row',
                                                    disable = list(columns = c(0)),
                                                    autoWidth = TRUE))
  
  output$vmt_forecast_sheet_tbl <- create_table(vmt_forecast_sheet,
                                                list(target = 'row',
                                                     disable = list(columns = c(0)),
                                                     autoWidth = TRUE))
  
  output$onroad_fuel_tech_frac_sheet_tbl <- create_table(onroad_fuel_tech_frac_sheet,
                                                         list(target = 'row',
                                                              disable = list(columns = c(0,1)),
                                                              autoWidth = TRUE))
  
  output$pass_rail_sheet_tbl <- create_table(pass_rail_sheet,
                                             list(target = 'row',
                                                  disable = list(columns = c(0,1)),
                                                  autoWidth = TRUE))
  
  output$freight_rail_sheet_tbl <- create_table(freight_rail_sheet,
                                                list(target = 'row',
                                                     disable = list(columns = c(0)),
                                                     autoWidth = TRUE))
  
  output$construction_sheet_tbl <- create_table(construction_sheet,
                                                list(target = 'row',
                                                     disable = list(columns = c(0)),
                                                     autoWidth = TRUE))
  
  output$fuel_apportionment_sheet_tbl <- create_table(fuel_apportionment_sheet,
                                                      list(target = 'row',
                                                           disable = list(columns = c(0)),
                                                           autoWidth = TRUE))
  
  ## make editable -----------------------------------------------------------
  
  
  
  observeEvent(input$ev_forecast_edit, {
    ev_forecast <<- editData(ev_forecast, input$ev_forecast_edit, 'ev_forecast_tbl')
  })
  
  
  observeEvent(input$vmt_forecast_edit, {
    vmt_forecast <<- editData(vmt_forecast, input$vmt_forecast_edit, 'vmt_forecast_tbl')
  })
  
  
  # server - outputs --------------------------------------------------------
  
  
  # server baseline outputs -------------------------------------------------
  
  # dummy data - copy pasta
  data_sample <- c(
    "Emissions (MT CO2e),2021,2025,2030,2050",
    "Light Duty Vehicles,16926661,17657202,17122996,16561171",
    "Medium and Heavy Duty Trucks,5594752,5580876,5264095,5261935",
    "Public Transit,120934,120934,120934,120934",
    "Passenger Rail,76608,76608,76608,76608",
    "Freight Rail,56162,57720,59729,68485",
    "Construction and Maintenance,0,0,0,0",
    "Total (Onroad Vehicles),22521413,23238078,22387092,21823105",
    "Total (All Transportation),22775117,23493340,22644362,22089133",
    "Change from Base Year (%),,3%,-1%,-3%"
  )
  
  dt <- rbindlist(lapply(data_sample, function(x) data.table(t(strsplit(x, ",")[[1]]))), use.names = TRUE, fill = TRUE)
  
  # better names, dropping first row, changing data stored as character to numeric
  setnames(dt, unlist(dt[1,]))
  dt <- dt[-1]
  numeric_columns <- names(dt)[!names(dt) %in% c("Emissions (MT CO2e)", "Change from Base Year (%)")]
  dt[, (numeric_columns) := lapply(.SD, function(x) as.numeric(gsub(",", "", x))), .SDcols = numeric_columns]
  
  # next time just upload a table
  
  output$baseline_outputs <- renderDT({
    DT::datatable(dt,
                  escape = FALSE,
                  options = list(pageLength = 10,
                                 autoWidth = FALSE,
                                 buttons = c('csv', 'excel')
                  ),
                  extensions = 'Buttons',
                  filter = 'bottom',
                  rownames = FALSE)
  })
  
  
  # server costs outputs ----------------------------------------------------
  
  costs_outputs_names <- c("bikeped_costs_outputs",
                           "transit_fixed_costs_outputs",
                           "transit_dr_costs_outputs",
                           "pub_trans_priority_costs_outputs",
                           "transit_zeb_costs_outputs",
                           "pub_trans_rail_costs_outputs",
                           "tdm_costs_outputs",
                           "micro_costs_outputs",
                           "traffic_ops_costs_outputs",
                           "mhdev_costs_outputs",
                           "pnr_costs_outputs",
                           "evsi_costs_outputs",
                           "roadway_expand_costs_outputs",
                           "intermodal_costs_outputs")
  
  read_static_tables(".\\data\\costs_outputs.xlsx", costs_outputs_names)
  
  ## create tables -----------------------------------------------------------
  
  # note that the tables below are not using the editable table function
  
  output$bikeped_costs_outputs_tbl <- renderDT({
    datatable(bikeped_costs_outputs,
              extensions = c('RowGroup','Buttons'),
              options = list(rowGroup = list(columns = c(0)),
                             columnDefs = list(list(visible = FALSE,
                                                    targets = c(0))),
                             autoWidth = TRUE,
                             width = '100%',
                             dom = 'tB',
                             buttons = c('copy', 'csv', 'excel', 'pdf')),
              rownames = FALSE) |>
      formatRound(c(3:7),1)})
  
  output$transit_fixed_costs_outputs_tbl <- renderDT(transit_fixed_costs_outputs,
                                                     rownames = FALSE)
  
  output$transit_dr_costs_outputs_tbl <- renderDT(transit_dr_costs_outputs,
                                                  rownames = FALSE)
  
  output$pub_trans_priority_costs_outputs_tbl <- renderDT(pub_trans_priority_costs_outputs,
                                                          rownames = FALSE)
  
  output$transit_zeb_costs_outputs_tbl <- renderDT(transit_zeb_costs_outputs,
                                                   rownames = FALSE)
  
  output$pub_trans_rail_costs_outputs_tbl <- renderDT(pub_trans_rail_costs_outputs,
                                                      rownames = FALSE)
  
  output$tdm_costs_outputs_tbl <- renderDT(tdm_costs_outputs,
                                           rownames = FALSE)
  
  output$micro_costs_outputs_tbl <- renderDT(micro_costs_outputs,
                                             rownames = FALSE)
  
  output$traffic_ops_costs_outputs_tbl <- renderDT(traffic_ops_costs_outputs,
                                                   rownames = FALSE)
  
  output$mhdev_costs_outputs_tbl <- renderDT(mhdev_costs_outputs,
                                             rownames = FALSE)
  
  output$pnr_costs_outputs_tbl <- renderDT(pnr_costs_outputs,
                                           rownames = FALSE)
  
  output$evsi_costs_outputs_tbl <- renderDT(evsi_costs_outputs,
                                            rownames = FALSE)
  
  output$roadway_expand_costs_outputs_tbl <- renderDT(roadway_expand_costs_outputs,
                                                      rownames = FALSE)
  
  output$intermodal_costs_outputs_tbl <- renderDT(intermodal_costs_outputs,
                                                  rownames = FALSE)
  
  
  ## make editable -----------------------------------------------------------
  
  costs_outputs_names <- c("bikeped_costs_outputs",
                           "transit_fixed_costs_outputs",
                           "transit_dr_costs_outputs",
                           "pub_trans_priority_costs_outputs",
                           "transit_zeb_costs_outputs",
                           "pub_trans_rail_costs_outputs",
                           "tdm_costs_outputs",
                           "micro_costs_outputs",
                           "traffic_ops_costs_outputs",
                           "mhdev_costs_outputs",
                           "pnr_costs_outputs",
                           "evsi_costs_outputs",
                           "roadway_expand_costs_outputs",
                           "intermodal_costs_outputs")
  
  
  
  # server scenarios outputs ------------------------------------------------
  
  # read dummy data
  scenario_result <- readxl::read_excel(".\\data\\scenario_simplified.xlsx")
  
  observeEvent(input$scenario_indicator,{
    dat_temp <- scenario_result |> 
      filter( indicator== input$scenario_indicator, !is.na(mt_reduction)) |> 
      select(-'value',-'pct_reduction') |> 
      mutate(year = as.character(year)) |> 
      pivot_wider(names_from = scenario,
                  values_from = mt_reduction)
    
    output$emission_change_graph <- renderPlotly(
      dat_temp |> 
        plotly::plot_ly(x = ~year,
                        y = ~`Scenario 1`,
                        type = 'bar',
                        name = 'Scenario 1' ) |> 
        add_trace(y = ~ `Scenario 2`, name = 'Scenario 2'))
    
    output$emission_change_tbl <- DT::renderDataTable(
      DT::datatable(dat_temp,
                    escape = FALSE,
                    rownames=F,
                    options = list(dom = 't')))
    
  })
  
  output$downloadscenario_result <- downloadHandler(
    filename = function(){
      paste("scenario_results",
            Sys.Date(),
            ".csv",
            sep="")},
    content = function(file) {
      tbl_out= scenario_result |> 
        rename()
      write.csv(tbl_out, file,row.names = F)
    })
  
  


  #sl working ----
  source("processing_scripts/processing_Base_Projections.R", local = TRUE)
  #check for tables being edited
  
  # observeEvent(EmRate_by_Tech(), { ### be careful to add everything that could update your outputs
  #   browser()
  #   # source("processing_scripts/processing_freight.R")
  # })
  
  source("processing_scripts/processing_freight.R", local = T)
  #rvs update from different inputs
  #key_inputs update
  key_inputs_listen <- reactive({
    list(input$state_input,
         input$base_year,
         input$horizon_year_1,
         input$horizon_year_2,
         input$horizon_year_3,
         input$transportation_scope,
         input$scope_emissions,
         input$scope_fuels,
         input$vmt_forecast_input,
         input$ev_baseline_input,
         input$grid_emissions_input)
  })
  
  observeEvent(key_inputs_listen(),{
    #browser()
    print("RUNNING: Update rvs$Baseline key inputs")
    rvs$Baseline$state <- input$state_input
    rvs$Baseline$base_year <- input$base_year
    rvs$Baseline$horizon_year_1 <- input$horizon_year_1
    rvs$Baseline$horizon_year_2 <- input$horizon_year_2
    rvs$Baseline$horizon_year_3 <- input$horizon_year_3
    rvs$Baseline$trans_system_scope <- input$transportation_scope
    rvs$Baseline$include_electricity <- input$scope_emissions #do these match?
    rvs$Baseline$include_upstream_fuels <- input$scope_fuels
    rvs$Baseline$vmt_forecast <- input$vmt_forecast_input
    rvs$Baseline$veh_elec_baseline <- input$ev_baseline_input
    rvs$Baseline$elec_grid_emissions_net_zero <- input$grid_emissions_input
  })
  
}

# Run the application
shinyApp(ui, server)

