#library(shiny)
library(bslib)
library(tidyverse)
library(readxl)
library(data.table)
library(thematic)
library(shinyBS)   # tooltips, maybe - shinyBS uses bootstrap 3 and bslib uses 5
library(DT)
library(shinydashboard)
library(shinyWidgets)
library(htmltools)
library(plotly)


# load modules and source files
for (file in c(
  list.files(".//R//ui_components/",
             pattern = "*.R",
             full.names = TRUE ),
  list.files(".//R//server_components/",
             pattern = "*.R",
             full.names = TRUE ),
  list.files(".//R//utils/",
             pattern = "*.R",
             full.names = TRUE ),
  list.files(".//R//functions/",
             pattern = "*.R",
             full.names = TRUE )
)) {
  source(file, encoding = "utf8")
}


# read in data and assign a name from a list ------------------------------

read_static_tables <- function(file_name, sheet_names) {
  for (i in seq_along(sheet_names)) {
    assign(sheet_names[i], read_xlsx(file_name,
                                     sheet = i,
                                     skip = 1,
                                     col_names = TRUE), envir = .GlobalEnv)
  }
}


# render datatable, make editable -----------------------------------------


create_table = function(data, editable = 'row', server = TRUE, ...) {
  renderDT(data,
           selection = 'none',
           server = server,
           editable = editable,
           rownames = FALSE,
           ...)
}

create_graph <- function(data, indicator){

}


assumptions_names <- c("bikeped_assmps",
                       "transit_assmps",
                       "tdm_assmps",
                       "micro_assmps",
                       "traffic_ops_assmps",
                       "mhdv_assmps",
                       "pnr_assmps",
                       "evsi_assmps")


ui <- function(request) {
  tagList(
    # Leave this function for adding external resources
    # Application UI logic
    title = "",
    page_navbar(
      theme = bs_theme(
        version = 5,
        fg = "#0d204d", # this has the same CMYK values as #173A89 but 70% saturation on black as opposed to 46%
        primary = "#173A89", #2A8627
        base_font = font_google("Inter"),
        font_scale = NULL,
        preset = "pulse",
        bg = "#fff"
      ),
      tags$style(HTML(
        '
      .nav.navbar-nav .form-group.shiny-input-container {margin-bottom: 0; height: 50px;}
      .nav.navbar-nav .form-group.shiny-input-container > label {display: inline;}
        '
      )),
      title = "TEA-CART",
      sidebar = sidebar(fileInput("fileInput",
                                  "Upload file",
                                  accept = c(".xlsx")),
                        bsTooltip(id = "fileInput",
                                  "Upload the file generated by the TEA-CART tool with user inputs.",
                                  options = list(container = "body"),
                                  placement = "right"),
                        downloadButton("downloadData", "Save & Download"),
                        p("Remember to save and download data regularly while
                          entering or updating values.")),
      nav_panel(title = "Welcome",
                  p(),
                  #    h2("Transportation Evaluation and Carbon Reduction Tool (TEA-CART)"),
                  h3("About"),
                  p(),
                  p("The Transportation Evaluation and Carbon Reduction Tool (TEA-CART) is a
      comprehensive and dynamic tool aimed at assisting states with selecting
      and prioritizing transportation capital program investments to effectively
      support greenhouse gas (GHG) reduction. The tool is designed to accept
      inputs typically available during the programming process. It provides
      key outputs including:"),
      tags$ul(tags$li(p("A baseline inventory and forecast of GHG emissions.")),
              tags$li(p("GHG impacts of a capital program or a hypothetical set
                      of capital projects.")),
              tags$li(p("Information on cost-effectiveness of various project
                      types."))),
      h3("Version"),
      p("Version 1.8"),
      p("last updated December 8, 2023"),
      p("draft User Interface (UI) under development by Cambridge Systematics, Inc."),
      p("under contract to Georgetown Climate Center"),
      p("© Georgetown Climate Center"),
                ),
      nav_panel(title = "Inputs",
                navset_card_pill(
                  nav_panel(title = "Baseline",
                            fluidRow(
                              column(6,

                                     tabPanel(title = "Key Inputs"),
                                     p("Select the state, years, and scope of baseline GHG forecast."),

                                     selectInput("state_input",
                                                 "State:",
                                                 selected = NULL,
                                                 state.name),
                                     numericInput("base_year",
                                                  "Base Year:",
                                                  value = 2021,
                                                  min = 2021,
                                                  max = 2050,
                                                  step = 1),
                                     p(" "),
                                     numericInput("horizon_year_1",
                                                  "Horizon Year 1:",
                                                  value = 2025,
                                                  min = 2021,
                                                  max = 2050,
                                                  step = 1),
                                     p(" "),
                                     numericInput("horizon_year_2",
                                                  "Horizon Year 2:",
                                                  value = 2030,
                                                  min = 2021,
                                                  max = 2050,
                                                  step = 1),
                                     p(""),
                                     numericInput("horizon_year_3",
                                                  "Horizon Year 3:",
                                                  value = 2050,
                                                  min = 2021,
                                                  max = 2050,
                                                  step = 1),
                                     p(""),
                                     selectInput("transportation_scope",
                                                 "Transportation System Scope:",
                                                 c("All Roadways","NHS Only"),
                                                 "All Roadways"),
                                     selectInput("scope_emissions",
                                                 "Include Electricity",
                                                 c("Yes","No"),
                                                 "Yes"),
                                     selectInput("scope_fuels",
                                                 "Include Upstream Fuels",
                                                 c("Yes","No"),
                                                 "No"),
                                     bsTooltip("scope_fuels",
                                               "Upstream Fuels refer to emissions associated with the production, extraction, and transportation of liquid and gaseous fuels including gasoline, diesel and CPG.",
                                               "right",
                                               options = list(container = "body"))
                              )),
                            ),
                  nav_panel(title = "Projects",
                            fluidRow(
                              p(""),
                              #     h3("Bicycle and Pedestrian lane miles of new infrastructure"),
                              accordion(
                                accordion_panel(
                                  HTML('<span style ="font-size: 24px; font-weight: bold;">Bicycle and
           Pedestrian Lane Miles of New Infrastructure</span>'),
           "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
      tempor incididunt ut labore et dolore magna aliqua. Amet nulla facilisi
      morbi tempus iaculis urna id. Scelerisque in dictum non consectetur a
      erat. Cursus sit amet dictum sit amet justo donec enim diam. Egestas
      pretium aenean pharetra magna ac placerat vestibulum. Et tortor consequat
      id porta nibh venenatis cras sed felis. Facilisis magna etiam tempor
      orci eu lobortis elementum nibh. Leo vel fringilla est ullamcorper eget
      nulla. Habitasse platea dictumst quisque sagittis purus sit amet volutpat
      consequat. Justo nec ultrices dui sapien eget mi proin sed. Nulla
      facilisi nullam vehicula ipsum a arcu cursus vitae. Eu mi bibendum neque
      egestas congue quisque egestas. Ornare massa eget egestas purus viverra
      accumsan in nisl nisi. Risus sed vulputate odio ut enim. Sem nulla
      pharetra diam sit amet nisl. At urna condimentum mattis pellentesque id
      nibh tortor id. Nibh praesent tristique magna sit amet purus gravida
      quis blandit. Arcu cursus euismod quis viverra nibh cras pulvinar
      mattis. Elit sed vulputate mi sit amet. Id eu nisl nunc mi."
                                ),
      id = "acc1",
      open = FALSE
                              ),
      p(""),
      DT::dataTableOutput("bikeped_projs_tbl")
                            ),

      fluidRow(
        h3("Transit: Increased Fixed Route Service (new Vehicles Operating in Maximum Service)"),
        DT::dataTableOutput("transit_fixed_projs_tbl")
      ),
      fluidRow(
        h3("Transit: Increased Demand Response Service (new Vehicles Operating in Maximum Service)"),
        DT::dataTableOutput("transit_dr_projs_tbl")
      ),
      fluidRow(
        h3("Fleet Electrification (number of vehicles replaced)"),
        DT::dataTableOutput("transit_el_projs_tbl")
      ),
      fluidRow(
        h3("Public Transportation: Bus Priority Treatment (number of units)"),
        DT::dataTableOutput("transit_bus_projs_tbl")
      ),
      fluidRow(
        h3("Public Transportation: Rail (new Vehicles Operating in Maximum Service)"),
        DT::dataTableOutput("public_rail_projs_tbl")
      ),
      fluidRow(
        h3("Travel Demand Management (number of units)"),
        DT::dataTableOutput("tdm_projs_tbl")
      ),
      fluidRow(
        h3("Micromobility (number of units)"),
        DT::dataTableOutput("micro_projs_tbl")
      ),
      fluidRow(
        h3("Traffic Operations (number of intersection improvements)"),
        DT::dataTableOutput("traffic_ops_projs_tbl")
      ),
      fluidRow(
        h3("Medium- and Heavy-Duty Vehicle Replacement (number of Vehicles Replaced)"),
        DT::dataTableOutput("mhdev_projs_tbl")
      ),
      fluidRow(
        h3("Park & Ride (number of units)"),
        DT::dataTableOutput("pnr_projs_tbl")
      ),
      fluidRow(
        h3("EV Charging Infrastructure (number of units)"),
        DT::dataTableOutput("evsi_projs_tbl")
      ),
      fluidRow(
        h3("Freight Intermodal Facilities (number of new intermodal facilities)"),
        DT::dataTableOutput("freight_projs_tbl")
      ),
      fluidRow(
        h3("Roadway expansion (number of new lane-miles)"),
        DT::dataTableOutput("expansion_projs_tbl")
      ),

                            ),
                  nav_panel(title = "Assumptions",




                              fluidRow(
                                p(""),
                                h3("Bicycle and Pedestrian Data",
                                   tooltip(
                                     bsicons::bs_icon("info-circle",
                                                      title = ""),
                                     placement = "top",
                                     "Increasing the prior drive mode share will result in a larger reduction in VMT reduction and CO2.")
                                ),
                                p(""),
                                DT::dataTableOutput("bikeped_assmps_tbl")
                              ),
                              fluidRow(
                                p(""),
                                h3("Transit Data"),
                                p(""),
                                DT::dataTableOutput("transit_assmps_tbl")
                              ),
                              fluidRow(
                                p(""),
                                h3("Travel Demand Management (TDM) Data"),
                                p(""),
                                DT::dataTableOutput("tdm_assmps_tbl")
                              ),
                              fluidRow(
                                p(""),
                                h3("Micromobility Data"),
                                p(""),
                                DT::dataTableOutput("micro_assmps_tbl")
                              ),
                              fluidRow(
                                p(""),
                                h3("Traffic operations & roadway expansion  Data"),
                                p(""),
                                DT::dataTableOutput("traffic_ops_assmps_tbl")
                              ),
                              fluidRow(
                                p(""),
                                h3("Medium & heavy-duty vehicle replacement Data"),
                                p(""),
                              DT::dataTableOutput("mhdv_assmps_tbl")
                              ),
                              fluidRow(
                                p(""),
                                h3("Park & Ride Data"),
                                p(""),
                               DT::dataTableOutput("pnr_assmps_tbl")
                              ),
                              fluidRow(
                                p(""),
                                h3("Electric Vehicle charging infrastructure Data"),
                                p(""),
                                DT::dataTableOutput("evsi_assmps_tbl")
                              )




                            ),
                  nav_panel(title = "Costs",
                            fluidRow(
                              p(""),
                              h3("Bicycle & Pedestrian"),
                              p(""),
                              DT::dataTableOutput("bikeped_costs_tbl")
                            ),
                            fluidRow(
                              p(""),
                              h3("Transit: Fixed Route Service"),
                              p(""),
                              DT::dataTableOutput("transit_fixed_costs_tbl")
                            ),
                            fluidRow(
                              p(""),
                              h3("Transit: Demand Response Service"),
                              p(""),
                              DT::dataTableOutput("transit_dr_costs_tbl")
                            ),
                            fluidRow(
                              p(""),
                              h3("Public Transportation: Bus Priority Treatment"),
                              p(""),
                              DT::dataTableOutput("pub_trans_priority_costs_tbl")
                            ),
                            fluidRow(
                              p(""),
                              h3("Public Transportation: Rail"),
                              p(""),
                              DT::dataTableOutput("pub_trans_rail_costs_tbl")
                            ),
                            fluidRow(
                              p(""),
                              h3("Travel Demand Management"),
                              p(""),
                              DT::dataTableOutput("tdm_costs_tbl")
                            ),
                            fluidRow(
                              p(""),
                              h3("Micromobility"),
                              p(""),
                              DT::dataTableOutput("micro_costs_tbl")
                            ),
                            fluidRow(
                              p(""),
                              h3("Traffic Operations - Intersection"),
                              p(""),
                              DT::dataTableOutput("traffic_ops_costs_tbl")
                            ),
                            fluidRow(
                              p(""),
                              h3("Medium and Heavy Duty Vehicle Replacement (per-vehicle cost)"),
                              p(""),
                              DT::dataTableOutput("mhdev_costs_tbl")
                            ),
                            fluidRow(
                              p(""),
                              h3("Park & Ride"),
                              p(""),
                              DT::dataTableOutput("pnr_costs_tbl")
                            ),
                            fluidRow(
                              p(""),
                              h3("EV Charging Infrastructure"),
                              p(""),
                              DT::dataTableOutput("evsi_costs_tbl")
                            ),
                            fluidRow(
                              p(""),
                              h3("Roadway Expansion"),
                              p(""),
                              DT::dataTableOutput("roadway_expand_costs_tbl")
                            ),
                            fluidRow(
                              p(""),
                              h3("Fuel Price (2022)"),
                              p(""),
                              DT::dataTableOutput("fuel_costs_tbl")
                            ),
                            fluidRow(
                              p(""),
                              h3("Intermodal Freight Investment"),
                              p(""),
                              DT::dataTableOutput("intermodal_costs_tbl")
                            ),
                            ),
                  nav_panel(title = "Scenarios",
                            fluidRow(
                              p(""),
                              h3("Scenario Testing"),
                              p(""),
                              DT::dataTableOutput("scenario_tbl")
                            )
     ),
                  nav_panel(title = "Advanced",

                            fluidRow(
                              p(""),
                              h3("Custom Forecast: Percent of on-road vehicles that are EVs",
                                 tooltip(
                                   bsicons::bs_icon("info-circle",
                                                    title = ""),
                                   placement = "top",
                                   "Enter values as a whole number (differently stated, type '55' in a cell to indicate '55%').")
                              ),
                              p(""),
                              DT::dataTableOutput("ev_forecast_tbl")
                            ),

                            fluidRow(
                              h3("Custom Forecast: Vehicles Miled Traveled (VMT)"),
                              DT::dataTableOutput("vmt_forecast_tbl")
                            )

    )
                )),

      nav_panel(title = "Outputs",
                navset_card_pill(
                  placement = "above",
                  nav_panel(title = "Baseline GHG Forecast",

                            h2("Baseline GHG Forecast"),
                            h3("Transportation GHG Forecast"),

                            DT::dataTableOutput("baseline_outputs")

   ),
                  nav_panel(title = "Scenario and Strategy Summary",
                            fluidRow(
                              p(""),
                              title = "Select Indicator",
                              selectizeInput(inputId = "scenario_indicator",
                                             label = "Indicator",
                                             selected = 'em_mt_co2_change',
                                             choices = c( 
                                               'MT CO2e' = 'CO2',
                                               'VMT (Mile)' = 'VMT',
                                               'MT NOx' = 'Nox',
                                               'MT PM2.5' = 'PM2.5',
                                               'Daily Active Trips' = 'New Daily Active Trips')
                              )),
                            fluidRow(
                              column(6,
                                     DT::DTOutput('emission_change_tbl'),
                                     fluidRow(
                                       column(6,
                                              br(),
                                              downloadButton('downloadscenario_result', 'Download Results'))
                                     )),
                              column(6,
                                     plotlyOutput("emission_change_graph", width = "auto", height = "auto"))),
  ),
                  nav_panel(title = "Cost effectiveness",
                            fluidRow(
                              p(""),
                              p("All results are reported in terms of annual change per $M investment."),
                              h3("Bicycle & Pedestrian"),
                              p(""),
                              DT::dataTableOutput("bikeped_costs_outputs_tbl")
                            ),
                            fluidRow(
                              p(""),
                              h3("Transit: Increased Fixed Route Service"),
                              p(""),
                              DT::dataTableOutput("transit_fixed_costs_outputs_tbl")
                            ),
                            fluidRow(
                              p(""),
                              h3("Transit: Increased Demand Response Service"),
                              p(""),
                              DT::dataTableOutput("transit_dr_costs_outputs_tbl")
                            ),
                            fluidRow(
                              p(""),
                              h3("Public Transportation: Bus Priority Treatment"),
                              p(""),
                              DT::dataTableOutput("pub_trans_priority_costs_outputs_tbl")
                            ),
                            fluidRow(
                              p(""),
                              h3("Transit: Fleet Electrification"),
                              p(""),
                              DT::dataTableOutput("transit_zeb_costs_outputs_tbl")
                            ),
                            fluidRow(
                              p(""),
                              h3("Public Transportation: Rail"),
                              p(""),
                              DT::dataTableOutput("pub_trans_rail_costs_outputs_tbl")
                            ),
                            fluidRow(
                              p(""),
                              h3("Travel Demand Management"),
                              p(""),
                              DT::dataTableOutput("tdm_costs_outputs_tbl")
                            ),
                            fluidRow(
                              p(""),
                              h3("Micromobility"),
                              p(""),
                              DT::dataTableOutput("micro_costs_outputs_tbl")
                            ),
                            fluidRow(
                              p(""),
                              h3("Traffic Operations: Intersections"),
                              p(""),
                              DT::dataTableOutput("traffic_ops_costs_outputs_tbl")
                            ),
                            fluidRow(
                              p(""),
                              h3("Medium and Heavy Duty Vehicle Replacement (Electrification)"),
                              p(""),
                              DT::dataTableOutput("mhdev_costs_outputs_tbl")
                            ),
                            fluidRow(
                              p(""),
                              h3("Park & Ride"),
                              p(""),
                              DT::dataTableOutput("pnr_costs_outputs_tbl")
                            ),
                            fluidRow(
                              p(""),
                              h3("EV Charging Infrastructure"),
                              p(""),
                              DT::dataTableOutput("evsi_costs_outputs_tbl")
                            ),
                            fluidRow(
                              p(""),
                              h3("Roadway Expansion"),
                              p(""),
                              DT::dataTableOutput("roadway_expand_costs_outputs_tbl")
                            ),
                            fluidRow(
                              p(""),
                              h3("Intermodal Freight Investment"),
                              p(""),
                              DT::dataTableOutput("intermodal_costs_outputs_tbl")
                            )
 )
                )),
      nav_panel(title = "Sources",
                h2("Sources"),
                p("The following resources were used in developing the TEA-CART tool."),

                DT::dataTableOutput("source_table")
                ),
      nav_spacer(),
      nav_menu(
        title = tags$img(src = "GCC_Logo_Transparent_Stacked.png", height = "30px"),
        nav_item(tags$a("Visit", href = "https://www.georgetownclimate.org/", target = "_blank")))


    )

  )

}

# setting themes - golem probably wants them somewhere else
# enabling thematic
thematic::thematic_shiny(font = "auto")

# setting default ggplot theme
theme_set(theme_bw(base_size = 16))

# https://stackoverflow.com/questions/31013769/locking-r-shiny-dashboard-sidebar-shinydashboard
# https://rstudio.github.io/bslib/articles/sidebars/index.html


server <- function(input, output, session) {

  # server - front matter ---------------------------------------------------

  sources_data <- read_xlsx("sources.xlsx", sheet = 1, col_names = TRUE)

  output$source_table <- renderDT({
    DT::datatable(sources_data,
                  escape = FALSE,
                  options = list(pageLength = 10,
                                 autoWidth = FALSE,
                                 buttons = c('csv', 'excel')
                  ),
                  extensions = 'Buttons',
                  filter = 'bottom',
                  rownames = FALSE)
  })

  # server project inputs ---------------------------------------------------------

  projects_names <- c("bikeped_projs",
                      "transit_fixed_projs",
                      "transit_dr_projs",
                      "transit_el_projs",
                      "transit_bus_projs",
                      "public_rail_projs",
                      "tdm_projs",
                      "micro_projs",
                      "traffic_ops_projs",
                      "mhdev_projs",
                      "pnr_projs",
                      "evsi_projs",
                      "freight_projs",
                      "expansion_projs")

  read_static_tables("projects.xlsx", projects_names)



  ## create tables -----------------------------------------------------------

  output$bikeped_projs_tbl <- create_table(bikeped_projs,
                                           list(target = 'row',
                                                disable = list(columns = c(0,1)),
                                                autoWidth = TRUE))

  output$transit_fixed_projs_tbl <- create_table(transit_fixed_projs,
                                                 list(target = 'row',
                                                      disable = list(columns = c(0,1)),
                                                      autoWidth = TRUE))

  output$transit_dr_projs_tbl <- create_table(transit_dr_projs,
                                              list(target = 'row',
                                                   disable = list(columns = c(0,1)),
                                                   autoWidth = TRUE))

  output$transit_el_projs_tbl <- create_table(transit_el_projs,
                                              list(target = 'row',
                                                   disable = list(columns = c(0,1)),
                                                   autoWidth = TRUE))

  output$transit_bus_projs_tbl <- create_table(transit_bus_projs,
                                               list(target = 'row',
                                                    disable = list(columns = c(0,1)),
                                                    autoWidth = TRUE))

  output$public_rail_projs_tbl <- create_table(public_rail_projs,
                                               list(target = 'row',
                                                    disable = list(columns = c(0,1)),
                                                    autoWidth = TRUE))

  output$tdm_projs_tbl <- create_table(tdm_projs,
                                       list(target = 'row',
                                            disable = list(columns = c(0,1)),
                                            autoWidth = TRUE))

  output$micro_projs_tbl <- create_table(micro_projs,
                                         list(target = 'row',
                                              disable = list(columns = c(0,1)),
                                              autoWidth = TRUE))

  output$traffic_ops_projs_tbl <- create_table(traffic_ops_projs,
                                               list(target = 'row',
                                                    disable = list(columns = c(0,1)),
                                                    autoWidth = TRUE))

  output$mhdev_projs_tbl <- create_table(mhdev_projs,
                                         list(target = 'row',
                                              disable = list(columns = c(0,1)),
                                              autoWidth = TRUE))

  output$pnr_projs_tbl <- create_table(pnr_projs,
                                       list(target = 'row',
                                            disable = list(columns = c(0,1)),
                                            autoWidth = TRUE))

  output$evsi_projs_tbl <- create_table(evsi_projs,
                                        list(target = 'row',
                                             disable = list(columns = c(0,1)),
                                             autoWidth = TRUE))

  output$freight_projs_tbl <- create_table(freight_projs,
                                           list(target = 'row',
                                                disable = list(columns = c(0,1)),
                                                autoWidth = TRUE))

  output$expansion_projs_tbl <- create_table(expansion_projs,
                                             list(target = 'row',
                                                  disable = list(columns = c(0,1)),
                                                  autoWidth = TRUE))



  ## make tables editable ----------------------------------------------------

  projects_names <- c("bikeped_projs",
                      "transit_fixed_projs",
                      "transit_dr_projs",
                      "transit_el_projs",
                      "transit_bus_projs",
                      "public_rail_projs",
                      "tdm_projs",
                      "micro_projs",
                      "traffic_ops_projs",
                      "mhdev_projs",
                      "pnr_projs",
                      "evsi_projs",
                      "freight_projs",
                      "expansion_projs")

  observe(print(input$acc1))


  observeEvent(input$bikeped_projs_edit, {
    bikeped_projs <<- editData(bikeped_projs, input$bikeped_projs_edit, 'bikeped_projs_tbl')
  })

  observeEvent(input$transit_fixed_projs_edit, {
    transit_fixed_projs <<- editData(transit_fixed_projs, input$transit_fixed_projs_edit, 'transit_fixed_projs_tbl')
  })

  observeEvent(input$transit_dr_projs_edit, {
    transit_dr_projs <<- editData(transit_fixed_projs, input$transit_dr_projs_edit, 'transit_dr_projs_tbl')
  })

  observeEvent(input$transit_el_projs_edit, {
    transit_el_projs <<- editData(transit_fixed_projs, input$transit_el_projs_edit, 'transit_el_projs_tbl')
  })

  observeEvent(input$transit_bus_projs_edit, {
    transit_bus_projs <<- editData(transit_fixed_projs, input$transit_bus_projs_edit, 'transit_bus_projs_tbl')
  })

  observeEvent(input$public_rail_projs_edit, {
    public_rail_projs <<- editData(transit_fixed_projs, input$public_rail_projs_edit, 'public_rail_projs_tbl')
  })

  observeEvent(input$tdm_projs_edit, {
    tdm_projs <<- editData(transit_fixed_projs, input$tdm_projs_edit, 'tdm_projs_tbl')
  })

  observeEvent(input$micro_projs_edit, {
    micro_projs <<- editData(transit_fixed_projs, input$micro_projs_edit, 'micro_projs_tbl')
  })

  observeEvent(input$traffic_ops_projs_edit, {
    traffic_ops_projs <<- editData(transit_fixed_projs, input$traffic_ops_projs_edit, 'traffic_ops_projs_tbl')
  })

  observeEvent(input$mhdev_projs_edit, {
    mhdev_projs <<- editData(transit_fixed_projs, input$mhdev_projs_edit, 'mhdev_projs_tbl')
  })

  observeEvent(input$pnr_projs_edit, {
    pnr_projs <<- editData(transit_fixed_projs, input$pnr_projs_edit, 'pnr_projs_tbl')
  })

  observeEvent(input$evsi_projs_edit, {
    evsi_projs <<- editData(transit_fixed_projs, input$evsi_projs_edit, 'evsi_projs_tbl')
  })

  observeEvent(input$freight_projs_edit, {
    freight_projs <<- editData(transit_fixed_projs, input$freight_projs_edit, 'freight_projs_tbl')
  })

  observeEvent(input$expansion_projs_edit, {
    expansion_projs <<- editData(transit_fixed_projs, input$expansion_projs_edit, 'expansion_projs_tbl')
  })
  #



# server assumptions ------------------------------------------------------

  assumptions_names <- c("bikeped_assmps",
                         "transit_assmps",
                         "tdm_assmps",
                         "micro_assmps",
                         "traffic_ops_assmps",
                         "mhdv_assmps",
                         "pnr_assmps",
                         "evsi_assmps")


  read_static_tables("assumptions.xlsx", assumptions_names)


  ## create tables -----------------------------------------------------------


  output$bikeped_assmps_tbl <- create_table(bikeped_assmps,
                                            list(target = 'row',
                                                 disable = list(columns = c(0,1)),
                                                 autoWidth = TRUE))


  output$transit_assmps_tbl <- create_table(transit_assmps,
                                            list(target = 'row',
                                                 disable = list(columns = c(0,1)),
                                                 autoWidth = TRUE))


  output$tdm_assmps_tbl <- create_table(tdm_assmps,
                                        list(target = 'row',
                                             disable = list(columns = c(0,1)),
                                             autoWidth = TRUE))


  output$micro_assmps_tbl <- create_table(micro_assmps,
                                          list(target = 'row',
                                               disable = list(columns = c(0,1)),
                                               autoWidth = TRUE))


  output$traffic_ops_assmps_tbl <- create_table(traffic_ops_assmps,
                                                list(target = 'row',
                                                     disable = list(columns = c(0,1)),
                                                     autoWidth = TRUE))


  output$mhdv_assmps_tbl <- create_table(mhdv_assmps,
                                         list(target = 'row',
                                              disable = list(columns = c(0,1)),
                                              autoWidth = TRUE))


  output$pnr_assmps_tbl <- create_table(pnr_assmps,
                                        list(target = 'row',
                                             disable = list(columns = c(0)),
                                             autoWidth = TRUE))


  output$evsi_assmps_tbl <- create_table(evsi_assmps,
                                         list(target = 'row',
                                              disable = list(columns = c(0,1)),
                                              autoWidth = TRUE))


  ## make tables editable ----------------------------------------------------


  observeEvent(input$bikeped_assmps_edit, {
    bikeped_assmps <<- editData(bikeped_assmps, input$bikeped_assmps_edit, 'bikeped_assmps_tbl')
  })

  observeEvent(input$transit_assmps_edit, {
    transit_assmps <<- editData(transit_assmps, input$transit_assmps_edit, 'transit_assmps_tbl')
  })

  observeEvent(input$tdm_assmps_edit, {
    tdm_assmps <<- editData(tdm_assmps, input$tdm_assmps_edit, 'tdm_assmps_tbl')
  })

  observeEvent(input$micro_assmps_edit, {
    micro_assmps <<- editData(micro_assmps, input$micro_assmps_edit, 'micro_assmps_tbl')
  })

  observeEvent(input$traffic_ops_assmps_edit, {
    traffic_ops_assmps <<- editData(traffic_ops_assmps, input$traffic_ops_assmps_edit, 'traffic_ops_assmps_tbl')
  })

  observeEvent(input$mhdv_assmps_edit, {
    mhdv_assmps <<- editData(mhdv_assmps, input$mhdv_assmps_edit, 'mhdv_assmps_tbl')
  })

  observeEvent(input$pnr_assmps_edit, {
    pnr_assmps <<- editData(pnr_assmps, input$pnr_assmps_edit, 'pnr_assmps_tbl')
  })

  observeEvent(input$evsi_assmps_edit, {
    evsi_assmps <<- editData(evsi_assmps, input$evsi_assmps_edit, 'evsi_assmps_tbl')
  })



# costs inputs server ------------------------------------------------------------


  costs_names <- c("bikeped_costs",
                   "transit_fixed_costs",
                   "transit_dr_costs",
                   "pub_trans_priority_costs",
                   "tdm_costs",
                   "pub_trans_rail_costs",
                   "micro_costs",
                   "traffic_ops_costs",
                   "mhdev_costs",
                   "pnr_costs",
                   "evsi_costs",
                   "roadway_expand_costs",
                   "fuel_costs",
                   "intermodal_costs")

  read_static_tables("costs_inputs.xlsx", costs_names)


  ## create tables -----------------------------------------------------------

  output$bikeped_costs_tbl <- create_table(bikeped_costs,
                                           list(target = 'row',
                                                disable = list(columns = c(0,1)),
                                                autoWidth = TRUE))

  output$transit_fixed_costs_tbl <- create_table(transit_fixed_costs,
                                                 list(target = 'row',
                                                      disable = list(columns = c(0,1)),
                                                      autoWidth = TRUE))

  output$transit_dr_costs_tbl <- create_table(transit_dr_costs,
                                              list(target = 'row',
                                                   disable = list(columns = c(0,1)),
                                                   autoWidth = TRUE))

  output$pub_trans_priority_costs_tbl <- create_table(pub_trans_priority_costs,
                                                      list(target = 'row',
                                                           disable = list(columns = c(0,1)),
                                                           autoWidth = TRUE))

  output$pub_trans_rail_costs_tbl <- create_table(pub_trans_rail_costs,
                                                  list(target = 'row',
                                                       disable = list(columns = c(0,1)),
                                                       autoWidth = TRUE))

  output$tdm_costs_tbl <- create_table(tdm_costs,
                                       list(target = 'row',
                                            disable = list(columns = c(0,1)),
                                            autoWidth = TRUE))

  output$micro_costs_tbl <- create_table(micro_costs,
                                         list(target = 'row',
                                              disable = list(columns = c(0,1)),
                                              autoWidth = TRUE))

  output$traffic_ops_costs_tbl <- create_table(traffic_ops_costs,
                                               list(target = 'row',
                                                    disable = list(columns = c(0,1)),
                                                    autoWidth = TRUE))

  output$mhdev_costs_tbl <- create_table(mhdev_costs,
                                         list(target = 'row',
                                              disable = list(columns = c(0,1)),
                                              autoWidth = TRUE))

  output$pnr_costs_tbl <- create_table(pnr_costs,
                                       list(target = 'row',
                                            disable = list(columns = c(0,1)),
                                            autoWidth = TRUE))

  output$evsi_costs_tbl <- create_table(evsi_costs,
                                        list(target = 'row',
                                             disable = list(columns = c(0,1)),
                                             autoWidth = TRUE))

  output$roadway_expand_costs_tbl <- create_table(roadway_expand_costs,
                                                  list(target = 'row',
                                                       disable = list(columns = c(0,1)),
                                                       autoWidth = TRUE))

  output$fuel_costs_tbl <- create_table(fuel_costs,
                                        list(target = 'row',
                                             disable = list(columns = c(0,1)),
                                             autoWidth = TRUE))

  output$intermodal_costs_tbl <- create_table(intermodal_costs,
                                              list(target = 'row',
                                                   disable = list(columns = c(0,1)),
                                                   autoWidth = TRUE))


  ## make editable -----------------------------------------------------------

  observeEvent(input$bikeped_costs_edit, {
    bikeped_costs <<- editData(bikeped_costs, input$bikeped_costs_edit, 'bikeped_costs_tbl')
  })

  observeEvent(input$transit_fixed_costs_edit, {
    transit_fixed_costs <<- editData(transit_fixed_costs, input$transit_fixed_costs_edit, 'transit_fixed_costs_tbl')
  })

  observeEvent(input$transit_dr_costs_edit, {
    transit_dr_costs <<- editData(transit_dr_costs, input$transit_dr_costs_edit, 'transit_dr_costs_tbl')
  })

  observeEvent(input$pub_trans_priority_costs_edit, {
    pub_trans_priority_costs <<- editData(pub_trans_priority_costs, input$pub_trans_priority_costs_edit, 'pub_trans_priority_costs_tbl')
  })

  observeEvent(input$pub_trans_rail_costs_edit, {
    pub_trans_rail_costs <<- editData(pub_trans_rail_costs, input$pub_trans_rail_costs_edit, 'pub_trans_rail_costs_tbl')
  })

  observeEvent(input$tdm_costs_edit, {
    tdm_costs <<- editData(tdm_costs, input$tdm_costs_edit, 'tdm_costs_tbl')
  })

  observeEvent(input$micro_costs_edit, {
    micro_costs <<- editData(micro_costs, input$micro_costs_edit, 'micro_costs_tbl')
  })

  observeEvent(input$traffic_ops_costs_edit, {
    traffic_ops_costs <<- editData(traffic_ops_costs, input$traffic_ops_costs_edit, 'traffic_ops_costs_tbl')
  })

  observeEvent(input$mhdev_costs_edit, {
    mhdev_costs <<- editData(mhdev_costs, input$mhdev_costs_edit, 'mhdev_costs_tbl')
  })

  observeEvent(input$pnr_costs_edit, {
    pnr_costs <<- editData(pnr_costs, input$pnr_costs_edit, 'pnr_costs_tbl')
  })

  observeEvent(input$evsi_costs_edit, {
    evsi_costs <<- editData(evsi_costs, input$evsi_costs_edit, 'evsi_costs_tbl')
  })

  observeEvent(input$roadway_expand_costs_edit, {
    roadway_expand_costs <<- editData(roadway_expand_costs, input$roadway_expand_costs_edit, 'roadway_expand_costs_tbl')
  })

  observeEvent(input$fuel_costs_edit, {
    fuel_costs <<- editData(fuel_costs, input$fuel_costs_edit, 'fuel_costs_tbl')
  })

  observeEvent(input$intermodal_costs_edit, {
    intermodal_costs <<- editData(intermodal_costs, input$intermodal_costs_edit, 'intermodal_costs_tbl')
  })



# server scenarios inputs -------------------------------------------------


  strategy_names <- c("Bicycle and Pedestrian",
                      "Transit Service Expansion",
                      "Micromobility",
                      "Travel Demand Management",
                      "Park and Ride",
                      "Transit Electrification",
                      "MD/HD Truck Replacement",
                      "Electric Vehicle Charging Infra.",
                      "Intermodal Freight Investment",
                      "Traffic Operations",
                      "Roadway Expansion",
                      "Custom Projects")

  rowName <- function(scenario) {
    as.character(
      checkboxInput(paste0("row", gsub(" ", "", scenario)), label = scenario)
    )
  }
  rowNames <- vapply(strategy_names, rowName, character(1))
  
  dat <- data.frame(
    vapply(strategy_names, function(scenario){
      as.character(
        checkboxInput(paste0("col1-", gsub(" ", "", scenario)), label = NULL)
      )
    }, character(1)),
    vapply(strategy_names, function(scenario){
      as.character(
        checkboxInput(paste0("col2-", gsub(" ", "", scenario)), label = NULL)
      )
    }, character(1))
  )
  
  names(dat) <- c(
    as.character(checkboxInput("col1", label = "Scenario 1")),
    as.character(checkboxInput("col2", label = "Scenario 2"))
  )
  
  rownames(dat) <- rowNames
  
  output$scenario_tbl <- renderDT({
    datatable(
      dat,
      escape = FALSE,
      select = "none",
      options = list(
        columnDefs = list(list(targets = c(1, 2),
                               orderable = FALSE,
                               className = "dt-center")
        ),
        pageLength = 12,
        initComplete = JS(
          "function() {",
          "  $('#col1').on('click', function(){",
          "    var cboxes = $('[id^=col1-]');",
          "    var checked = $('#col1').is(':checked');",
          "    cboxes.each(function(i, cbox) {",
          "      $(cbox).prop('checked', checked);",
          "    });",
          "  });",
          "  $('#col2').on('click', function(){",
          "    var cboxes = $('[id^=col2-]');",
          "    var checked = $('#col2').is(':checked');",
          "    cboxes.each(function(i, cbox) {",
          "      $(cbox).prop('checked', checked);",
          "    });",
          "  });",
          paste(
            sapply(strategy_names, function(scenario) {
              scenarioId <- gsub(" ", "", scenario)
              sprintf(
                "  $('#row%s').on('click', function(){\n    var cboxes = $('[id$=\\'-%s\\']');\n    var checked = $('#row%s').is(':checked');\n    cboxes.each(function(i, cbox) {\n      $(cbox).prop('checked', checked);\n    });\n  });",
                scenarioId, scenarioId, scenarioId
              )
            }),
            collapse = "\n"
          ),
          "}"
        ),
        preDrawCallback =
          JS('function() { Shiny.unbindAll(this.api().table().node()); }'),
        drawCallback =
          JS('function() { Shiny.bindAll(this.api().table().node()); } ')
      )
    )
  })
  


# server advanced inputs ---------------------------------------------------------

  advanced_names <- c("ev_forecast",
                      "vmt_forecast")


  read_static_tables <- function(file_name, sheet_names) {
    for (i in seq_along(sheet_names)) {
      assign(sheet_names[i], read_xlsx(file_name,
                                       sheet = i,
                                       skip = 1,
                                       col_names = TRUE), envir = .GlobalEnv)
    }
  }

  read_static_tables("advanced.xlsx", advanced_names)


  create_table = function(data, editable = 'row', server = TRUE, ...) {
    renderDT(data,
             selection = 'none',
             server = server,
             editable = editable,
             rownames = FALSE,
             ...)
  }

  create_graph <- function(data, indicator){

  }


  ## create tables -----------------------------------------------------------

  output$ev_forecast_tbl <- create_table(ev_forecast,
                                         list(target = 'row',
                                              disable = list(columns = c(0)),
                                              autoWidth = TRUE))

  output$vmt_forecast_tbl <- create_table(vmt_forecast,
                                          list(target = 'row',
                                               disable = list(columns = c(0)),
                                               autoWidth = TRUE))

  ## make editable -----------------------------------------------------------



  observeEvent(input$ev_forecast_edit, {
    ev_forecast <<- editData(ev_forecast, input$ev_forecast_edit, 'ev_forecast_tbl')
  })


  observeEvent(input$vmt_forecast_edit, {
    vmt_forecast <<- editData(vmt_forecast, input$vmt_forecast_edit, 'vmt_forecast_tbl')
  })


  # server - outputs --------------------------------------------------------


# server baseline outputs -------------------------------------------------

  # dummy data - copy pasta
  data_sample <- c(
    "Emissions (MT CO2e),2021,2025,2030,2050",
    "Light Duty Vehicles,16926661,17657202,17122996,16561171",
    "Medium and Heavy Duty Trucks,5594752,5580876,5264095,5261935",
    "Public Transit,120934,120934,120934,120934",
    "Passenger Rail,76608,76608,76608,76608",
    "Freight Rail,56162,57720,59729,68485",
    "Construction and Maintenance,0,0,0,0",
    "Total (Onroad Vehicles),22521413,23238078,22387092,21823105",
    "Total (All Transportation),22775117,23493340,22644362,22089133",
    "Change from Base Year (%),,3%,-1%,-3%"
  )

  dt <- rbindlist(lapply(data_sample, function(x) data.table(t(strsplit(x, ",")[[1]]))), use.names = TRUE, fill = TRUE)

  # better names, dropping first row, changing data stored as character to numeric
  setnames(dt, unlist(dt[1,]))
  dt <- dt[-1]
  numeric_columns <- names(dt)[!names(dt) %in% c("Emissions (MT CO2e)", "Change from Base Year (%)")]
  dt[, (numeric_columns) := lapply(.SD, function(x) as.numeric(gsub(",", "", x))), .SDcols = numeric_columns]

  # next time just upload a table

  output$baseline_outputs <- renderDT({
    DT::datatable(dt,
                  escape = FALSE,
                  options = list(pageLength = 10,
                                 autoWidth = FALSE,
                                 buttons = c('csv', 'excel')
                  ),
                  extensions = 'Buttons',
                  filter = 'bottom',
                  rownames = FALSE)
  })


# server costs outputs ----------------------------------------------------

  costs_outputs_names <- c("bikeped_costs_outputs",
                           "transit_fixed_costs_outputs",
                           "transit_dr_costs_outputs",
                           "pub_trans_priority_costs_outputs",
                           "transit_zeb_costs_outputs",
                           "pub_trans_rail_costs_outputs",
                           "tdm_costs_outputs",
                           "micro_costs_outputs",
                           "traffic_ops_costs_outputs",
                           "mhdev_costs_outputs",
                           "pnr_costs_outputs",
                           "evsi_costs_outputs",
                           "roadway_expand_costs_outputs",
                           "intermodal_costs_outputs")

  read_static_tables("costs_outputs.xlsx", costs_outputs_names)

  ## create tables -----------------------------------------------------------

  # note that the tables below are not using the editable table function

  output$bikeped_costs_outputs_tbl <- renderDT({
    datatable(bikeped_costs_outputs,
              extensions = c('RowGroup','Buttons'),
              options = list(rowGroup = list(columns = c(0)),
                             columnDefs = list(list(visible = FALSE,
                                                    targets = c(0))),
                             autoWidth = TRUE,
                             width = '100%',
                             dom = 'tB',
                             buttons = c('copy', 'csv', 'excel', 'pdf')),
              rownames = FALSE) |>
      formatRound(c(3:7),1)})

  output$transit_fixed_costs_outputs_tbl <- renderDT(transit_fixed_costs_outputs,
                                                     rownames = FALSE)

  output$transit_dr_costs_outputs_tbl <- renderDT(transit_dr_costs_outputs,
                                                  rownames = FALSE)

  output$pub_trans_priority_costs_outputs_tbl <- renderDT(pub_trans_priority_costs_outputs,
                                                          rownames = FALSE)

  output$transit_zeb_costs_outputs_tbl <- renderDT(transit_zeb_costs_outputs,
                                                   rownames = FALSE)

  output$pub_trans_rail_costs_outputs_tbl <- renderDT(pub_trans_rail_costs_outputs,
                                                      rownames = FALSE)

  output$tdm_costs_outputs_tbl <- renderDT(tdm_costs_outputs,
                                           rownames = FALSE)

  output$micro_costs_outputs_tbl <- renderDT(micro_costs_outputs,
                                             rownames = FALSE)

  output$traffic_ops_costs_outputs_tbl <- renderDT(traffic_ops_costs_outputs,
                                                   rownames = FALSE)

  output$mhdev_costs_outputs_tbl <- renderDT(mhdev_costs_outputs,
                                             rownames = FALSE)

  output$pnr_costs_outputs_tbl <- renderDT(pnr_costs_outputs,
                                           rownames = FALSE)

  output$evsi_costs_outputs_tbl <- renderDT(evsi_costs_outputs,
                                            rownames = FALSE)

  output$roadway_expand_costs_outputs_tbl <- renderDT(roadway_expand_costs_outputs,
                                                      rownames = FALSE)

  output$intermodal_costs_outputs_tbl <- renderDT(intermodal_costs_outputs,
                                                  rownames = FALSE)


  # make editable -----------------------------------------------------------

  costs_outputs_names <- c("bikeped_costs_outputs",
                           "transit_fixed_costs_outputs",
                           "transit_dr_costs_outputs",
                           "pub_trans_priority_costs_outputs",
                           "transit_zeb_costs_outputs",
                           "pub_trans_rail_costs_outputs",
                           "tdm_costs_outputs",
                           "micro_costs_outputs",
                           "traffic_ops_costs_outputs",
                           "mhdev_costs_outputs",
                           "pnr_costs_outputs",
                           "evsi_costs_outputs",
                           "roadway_expand_costs_outputs",
                           "intermodal_costs_outputs")



# server scenarios outputs ------------------------------------------------

  # read dummy data
  scenario_result <- readxl::read_excel("scenario_simplified.xlsx")

  observeEvent(input$scenario_indicator,{
    dat_temp <- scenario_result %>%
      filter( indicator== input$scenario_indicator, !is.na(mt_reduction)) %>%
      select(-'value',-'pct_reduction') %>%
      mutate(year = as.character(year)) %>%
      pivot_wider(names_from = scenario,
                  values_from = mt_reduction)

    output$emission_change_graph <- renderPlotly(
      dat_temp %>%
        plotly::plot_ly(x = ~year,
                        y = ~`Scenario 1`,
                        type = 'bar',
                        name = 'Scenario 1' ) %>%
        add_trace(y = ~ `Scenario 2`, name = 'Scenario 2'))

    output$emission_change_tbl <- DT::renderDataTable(
      DT::datatable(dat_temp,
                    escape = FALSE,
                    rownames=F,
                    options = list(dom = 't')))

  })

  output$downloadscenario_result <- downloadHandler(
    filename = function(){
      paste("scenario_results",Sys.Date(), ".csv", sep="")},
    content = function(file) {
      tbl_out= scenario_result %>%
        rename()
      write.csv(tbl_out, file,row.names = F)
    })




}

# Run the application
shinyApp(ui, server)

